In [304]:
import pandas as pd

In [305]:
df = pd.read_csv('test.csv')

In [306]:
import os

In [307]:
print(os.getcwd())

C:\Users\admin

In [308]:
os.listdir()

['.ai-navigator',
 '.anaconda',
 '.astropy',
 '.atom',
 '.conda',
 '.condarc',
 '.continuum',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.matplotlib',
 '.nuget',
 '.thumbnails',
 '.VirtualBox',
 '.virtual_documents',
 '.vscode',
 '3d abc song chill',
 'anaconda_projects',
 'AppData',
 'Application Data',
 'Contacts',
 'Cookies',
 'Desktop',
 'DFWNov.csv',
 'DLX 2 ROCKY METAL LOUDER CYMBALS.ssd5kit',
 'Documents',
 'Downloads',
 'environment.yml',
 'Favorites',
 'GameMakerProjects',
 'IntelGraphicsProfiles',
 'jack.iom',
 'jacks.2ssd5kit.ssd5kit',
 'jacks.iom',
 'KIDS SHOW',
 'Links',
 'Local Settings',
 'Models and NPCs',
 'Music',
 'My Documents',
 'NCH Software Suite',
 'NetHood',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{a2332f18-cdbf-11ec-8680-002248483d79}.TM.blf',
 'NTUSER.DAT{a2332f18-cdbf-11ec-8680-002248483d79}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{a2332f18-cdbf-11ec-8680-002248483d79}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'PaceKeyChain',
 'Pictures',
 'PrintHood',
 'Proton Drive',
 'Recent',
 'Saved Games',
 'SciFi 3D',
 'Searches',
 'SendTo',
 'source',
 'Start Menu',
 'Templates',
 'test.csv',
 'Untitled.ipynb',
 'Untitled1.ipynb',
 'Untitled2.ipynb',
 'Untitled3.ipynb',
 'Videos']

In [328]:
df = pd.read_csv('DFWNov.csv')
df

,Estimated Equity,Estimated Margin percent,Est Unpaid Bal,Clerk Number,Year of Report,Month of Report,City Name,County Code,Mapsco Page,Mapsco Section,...,Owner Street Name,Owner Zip,Owner City,Owner State,Tax ID,Status,OpeningBid,Auction Date,Georeference,Zillow URL
0,289574.0,75.0,96706,0,2024,12,ADDISON,DA,NaN,NaN,...,PLANTERS ROW,75001,ADDISON,TX,100006500B0160000,NaN,0,December,http://www.zillow.com/homes/17073-PLANTERS-ROW...,NaN
1,NaN,NaN,0,0,2024,12,ADDISON,DA,NaN,NaN,...,BREEDLOVE PLACE #153,75001,ADDISON,TX,10C05500001700153,NaN,0,December,http://www.zillow.com/homes/15848-BREEDLOVE-PL...,NaN
2,NaN,NaN,0,0,2024,12,ADDISON,DA,NaN,NaN,...,SPECTRUM DR # 176,75001,ADDISON,TX,10C05500002000176,NaN,0,December,http://www.zillow.com/homes/15811-SPECTRUM-DR-...,NaN
3,235426.0,69.0,107444,0,2024,12,BALCH SPRINGS,DA,NaN,NaN,...,BROADVIEW DR,75180,BALCH SPRINGS,TX,120798000M0240000,NaN,0,December,http://www.zillow.com/homes/14718-BROADVIEW-DR...,NaN
4,108425.0,48.0,115535,0,2024,12,BALCH SPRINGS,DA,NaN,NaN,...,MARSHA DR,75180,BALCH SPRINGS,TX,12077500050260000,NaN,0,December,http://www.zillow.com/homes/14910-MARSHA-DR-N_rb/,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
293,NaN,NaN,0,0,2024,12,ROWLETT,DA,NaN,NaN,...,LIBERTY GROVE RD,75089,ROWLETT,TX,0,NaN,0,December,http://www.zillow.com/homes/10206-LIBERTY-GROV...,NaN
294,74963.0,23.0,246587,0,2024,12,SEAGOVILLE,DA,NaN,NaN,...,ARMSTRONG RD,75159,SEAGOVILLE,TX,500230000F0030000,NaN,0,December,http://www.zillow.com/homes/910-ARMSTRONG-RD-N...,NaN
295,72023.0,24.0,222307,0,2024,12,SEAGOVILLE,DA,NaN,NaN,...,S GREAT SOUTHWEST PKWY APT 134,75051,GRAND PRAIRIE,TX,50044500040010000,NaN,0,December,http://www.zillow.com/homes/531-JUDY-LN-N_rb/,NaN
296,239461.0,86.0,37699,0,2024,12,SEAGOVILLE,DA,NaN,NaN,...,COLONIAL CIR,75159,SEAGOVILLE,TX,50009920000010000,NaN,0,December,http://www.zillow.com/homes/100-COLONIAL-CIRCL...,NaN
297,60991.0,22.0,212429,0,2024,12,SUNNYVALE,DA,NaN,NaN,...,WIXOM LN,75217,DALLAS,TX,65123639010640000,NaN,0,December,http://www.zillow.com/homes/541-POLLY-RD-N_rb/,NaN

In [329]:
# Selecting the required columns
dfrev1 = df[[
    'Mortgagor First Name',
    'Mortgagor Last Name',
    'Owner Street Number',
    'Owner Street Name',
    'City Name',
    'Estimated Equity', 
    'Estimated Margin percent'
]]

# Including rows 53, 216, and 261
dfrev1_selected = dfrev1.iloc[[53, 216, 261]]

print(dfrev1_selected)
dfrev1_selected

    Mortgagor First Name Mortgagor Last Name  Owner Street Number  \
53        MARCUS D/COREY            FURLOUGH                 1846
216                CAMIE        SANCHEZ ETAL                  784
261              DERRICK               BATTS                 1935

    Owner Street Name  City Name  Estimated Equity  Estimated Margin percent
53     E LEDBETTER DR     DALLAS          246979.0                      99.0
216           HALL RD    GARLAND          361484.0                      99.0
261          RYDER DR  LANCASTER          266035.0                      99.0

,Mortgagor First Name,Mortgagor Last Name,Owner Street Number,Owner Street Name,City Name,Estimated Equity,Estimated Margin percent
53,MARCUS D/COREY,FURLOUGH,1846,E LEDBETTER DR,DALLAS,246979.0,99.0
216,CAMIE,SANCHEZ ETAL,784,HALL RD,GARLAND,361484.0,99.0
261,DERRICK,BATTS,1935,RYDER DR,LANCASTER,266035.0,99.0

In [330]:
df.isnull().sum()

Estimated Equity             37
Estimated Margin percent     37
Est Unpaid Bal                0
Clerk Number                  0
Year of Report                0
Month of Report               0
City Name                     0
County Code                   0
Mapsco Page                 298
Mapsco Section              298
Class                         0
Loan Type                     0
Street Number                 0
Address                       0
B/B/G                         8
Property Sq Footage           0
Pool                         20
Zip                           0
Legal Description 1           0
Legal Description 2           1
Subdivision                   0
Mortgagor First Name         36
Mortgagor Last Name          28
Mortgagee                     0
Trustee                       0
Auction Sale Time             0
Volume                        0
Page                          0
Loan Month                    0
Loan Year                     0
Original Loan Amount          0
Monthly Payment               0
Interest Rate                 0
Loan Expires Month            0
Loan Expires Year             0
Year Of Construction          0
Assessed Value                0
City Code                     0
Number of Units               0
Previous Posting            171
Comment                     254
Owner Street Number           0
Owner Street Name             0
Owner Zip                     0
Owner City                    0
Owner State                   0
Tax ID                        0
Status                      298
OpeningBid                    0
Auction Date                  0
Georeference                  0
Zillow URL                  298
dtype: int64

In [331]:
df.isnull().sum().sum()

1784

In [332]:
df_sorted_desc = dfrev1.sort_values(by='Estimated Margin percent', ascending=False)
print(df_sorted_desc)
df_sorted_desc.head()

    Mortgagor First Name              Mortgagor Last Name  \
53        MARCUS D/COREY                         FURLOUGH
216                CAMIE                     SANCHEZ ETAL
261              DERRICK                            BATTS
43                 ANNIE                             HUFF
7         WILFREDO PEREZ                     MENDEZ ET AL
..                   ...                              ...
285                  NaN  SERENITY SENIOR LIVING I I  LLC
287   GUANITA D/ARLUSTER                  WRIGHT JR  ETAL
291            MUSTAFA S                            BELLO
292               PIERRE                          TURRELL
293                  NaN                 WATER SPRING LLC

     Owner Street Number Owner Street Name      City Name  Estimated Equity  \
53                  1846    E LEDBETTER DR         DALLAS          246979.0
216                  784           HALL RD        GARLAND          361484.0
261                 1935          RYDER DR      LANCASTER          266035.0
43                  1928      MATAGORDA DR         DALLAS          324675.0
7                   3813    FOREST LAWN RD  BALCH SPRINGS          155460.0
..                   ...               ...            ...               ...
285                    0     PO BOX 851573       MESQUITE               NaN
287                  800    BRIDGEWATER LN       MESQUITE               NaN
291                  655        MATTHEW PL     RICHARDSON               NaN
292                 7941       CHAPMAN CIR        ROWLETT               NaN
293                10206  LIBERTY GROVE RD        ROWLETT               NaN

     Estimated Margin percent
53                       99.0
216                      99.0
261                      99.0
43                       99.0
7                        99.0
..                        ...
285                       NaN
287                       NaN
291                       NaN
292                       NaN
293                       NaN

[298 rows x 7 columns]

,Mortgagor First Name,Mortgagor Last Name,Owner Street Number,Owner Street Name,City Name,Estimated Equity,Estimated Margin percent
53,MARCUS D/COREY,FURLOUGH,1846,E LEDBETTER DR,DALLAS,246979.0,99.0
216,CAMIE,SANCHEZ ETAL,784,HALL RD,GARLAND,361484.0,99.0
261,DERRICK,BATTS,1935,RYDER DR,LANCASTER,266035.0,99.0
43,ANNIE,HUFF,1928,MATAGORDA DR,DALLAS,324675.0,99.0
7,WILFREDO PEREZ,MENDEZ ET AL,3813,FOREST LAWN RD,BALCH SPRINGS,155460.0,99.0

In [333]:
# Top 20 highest percentages
top_20_highest = dfrev1.sort_values(by='Estimated Margin percent', ascending=False).head(20)
print("Top 20 Highest Percentages:\n", top_20_highest)

# Top 20 lowest percentages
top_20_lowest = dfrev1.sort_values(by='Estimated Margin percent', ascending=True).head(20)
print("Top 20 Lowest Percentages:\n", top_20_lowest)
top_20_highest

Top 20 Highest Percentages:
       Mortgagor First Name Mortgagor Last Name  Owner Street Number  \
53          MARCUS D/COREY            FURLOUGH                 1846
216                  CAMIE        SANCHEZ ETAL                  784
261                DERRICK               BATTS                 1935
43                   ANNIE                HUFF                 1928
7           WILFREDO PEREZ        MENDEZ ET AL                 3813
231                 RODNEY      DE BAUN   ETAL                 4435
58                  ARTURO            GARCIA V                 9905
239       CARLOS/CHRISTINA             MORALES                 4402
211                  DAVID           ARCHULETA                 2413
106        KATHERINE/PETER             STANTON                 7829
236               SANTIAGO       ZAMBRANO ETAL                  626
61                   JAMES             JOHNSON                 4446
129                 MIRIAN  FIERRO MEJIA ET AL                 5007
203                   GLEN         BAILEY ETAL                 1810
107                CASEY A               BATES                 4721
12              TERRENCE G                 ORR                 1038
18      RUSSELL M/JAMITA J              MACHEN                 1547
57          MARIA A/MIGUEL             MARCELO                 1619
126  LEXIAM PROPERTIES LLC                 NaN                    0
159          HIRLA DANIELA             MERCADO                 3950

          Owner Street Name      City Name  Estimated Equity  \
53           E LEDBETTER DR         DALLAS          246979.0
216                 HALL RD        GARLAND          361484.0
261                RYDER DR      LANCASTER          266035.0
43             MATAGORDA DR         DALLAS          324675.0
7            FOREST LAWN RD  BALCH SPRINGS          155460.0
231                ARBOR LN  GRAND PRAIRIE          229515.0
58               HUSTEAD ST         DALLAS          207499.0
239          GREEN ACRES CT  GRAND PRAIRIE          218568.0
211            HIGH STAR DR        GARLAND          261278.0
106          EL PENSADOR DR         DALLAS          483964.0
236               AUSTIN ST  GRAND PRAIRIE         2148286.0
61                CICERO ST         DALLAS         1141682.0
129            BARTLETT AVE         DALLAS          129107.0
203             PATRICIA LN        GARLAND          269604.0
107  BRADFORD DR UNIT 4721B         DALLAS         2656896.0
12             HAMPSHIRE LN     CEDAR HILL          317915.0
18          CYPRESS BEND DR     CEDAR HILL          636526.0
57               ALASKA AVE         DALLAS          221795.0
126            PO BOX 29566         DALLAS          342975.0
159          DEEP VALLEY DR         DALLAS          707891.0

     Estimated Margin percent
53                       99.0
216                      99.0
261                      99.0
43                       99.0
7                        99.0
231                      98.0
58                       98.0
239                      98.0
211                      98.0
106                      98.0
236                      97.0
61                       97.0
129                      97.0
203                      97.0
107                      96.0
12                       96.0
18                       96.0
57                       95.0
126                      95.0
159                      95.0
Top 20 Lowest Percentages:
               Mortgagor First Name         Mortgagor Last Name  \
145       GUESTWISER VENTURE 1 LLC                         NaN
154          LUX HOMES CORPORATION                         NaN
156          HANDY ANDY & SONS LLC                         NaN
142                          LUCIO                       NUNEZ
133        FOCIS HOLDING GROUP LLC                         NaN
122              HOUSE OF DEFI LLC                         NaN
130            MAGNOLIA NOELLE LLC                         NaN
120  PEOPLE PRIORITY SOLUTIONS LLC                         NaN
271                     CORDERAL D                        CARR
141                          NUBIA                      TORRES
84                             NaN  EXECUTIVE REALTY GROUP LLC
228                          EDITH                ANDRADE ETAL
128                CHESS HOMES LLC                         NaN
149                         VIVIAN                    GONZALEZ
166                     ELAINE SUE                      LEVINE
119                            NaN     OWNOLOGY INVESTMENT LLC
88                             NaN     ABC LEGACY VENTURES LLC
125        5014 GARLAND AVENUE LLC                         NaN
221              VILLA PLACITA LLC                         NaN
262                KRISTI/ORRICK D                        LACY

     Owner Street Number      Owner Street Name      City Name  \
145                 7083    HOLLYWOOD BLVD FL 5         DALLAS
154                    0            PO BOX 1502         DALLAS
156                 1355            DELL OAK DR         DALLAS
142                 2664              BONITA DR         DALLAS
133                 6020       WORTH ST APT 100         DALLAS
122                 2230                KESSLER         DALLAS
130                 4020       MACARTHUR BLVD N         DALLAS
120                  308             DUXBURY CT         DALLAS
271                  204             KEARNEY ST       MESQUITE
141                 6230          MILITARY PKWY         DALLAS
84                   305  SPRING CREEK VLG #494         DALLAS
228                 1425             CHESTER ST  GRAND PRAIRIE
128                  213        FOX HOLLOW BLVD         DALLAS
149                 7904             BENTLEY DR         DALLAS
166                12578          MONTEGO PLAZA         DALLAS
119                 1815            PERRYTON DR         DALLAS
88                  1020         ALAMO DR # 300         DALLAS
125                13101  PRESTON RD STE 110826         DALLAS
221                 2840         KELLER SPRINGS        GARLAND
262                 1329            ROSEWOOD LN      LANCASTER

     Estimated Equity  Estimated Margin percent
145        -2433806.0                    -913.0
154         -683880.0                    -760.0
156         -314000.0                    -374.0
142         -740831.0                    -315.0
133         -126629.0                    -233.0
122         -609357.0                    -215.0
130         -742473.0                     -48.0
120          -49820.0                     -38.0
271          -70575.0                     -33.0
141          -19263.0                     -20.0
84           -26250.0                     -18.0
228          -42313.0                     -18.0
128          -76042.0                     -17.0
149          -26322.0                     -13.0
166          -34235.0                      -7.0
119          -10970.0                      -7.0
88           -33130.0                      -5.0
125            8153.0                       1.0
221          212215.0                       2.0
262            7579.0                       3.0

,Mortgagor First Name,Mortgagor Last Name,Owner Street Number,Owner Street Name,City Name,Estimated Equity,Estimated Margin percent
53,MARCUS D/COREY,FURLOUGH,1846,E LEDBETTER DR,DALLAS,246979.0,99.0
216,CAMIE,SANCHEZ ETAL,784,HALL RD,GARLAND,361484.0,99.0
261,DERRICK,BATTS,1935,RYDER DR,LANCASTER,266035.0,99.0
43,ANNIE,HUFF,1928,MATAGORDA DR,DALLAS,324675.0,99.0
7,WILFREDO PEREZ,MENDEZ ET AL,3813,FOREST LAWN RD,BALCH SPRINGS,155460.0,99.0
231,RODNEY,DE BAUN ETAL,4435,ARBOR LN,GRAND PRAIRIE,229515.0,98.0
58,ARTURO,GARCIA V,9905,HUSTEAD ST,DALLAS,207499.0,98.0
239,CARLOS/CHRISTINA,MORALES,4402,GREEN ACRES CT,GRAND PRAIRIE,218568.0,98.0
211,DAVID,ARCHULETA,2413,HIGH STAR DR,GARLAND,261278.0,98.0
106,KATHERINE/PETER,STANTON,7829,EL PENSADOR DR,DALLAS,483964.0,98.0
236,SANTIAGO,ZAMBRANO ETAL,626,AUSTIN ST,GRAND PRAIRIE,2148286.0,97.0
61,JAMES,JOHNSON,4446,CICERO ST,DALLAS,1141682.0,97.0
129,MIRIAN,FIERRO MEJIA ET AL,5007,BARTLETT AVE,DALLAS,129107.0,97.0
203,GLEN,BAILEY ETAL,1810,PATRICIA LN,GARLAND,269604.0,97.0
107,CASEY A,BATES,4721,BRADFORD DR UNIT 4721B,DALLAS,2656896.0,96.0
12,TERRENCE G,ORR,1038,HAMPSHIRE LN,CEDAR HILL,317915.0,96.0
18,RUSSELL M/JAMITA J,MACHEN,1547,CYPRESS BEND DR,CEDAR HILL,636526.0,96.0
57,MARIA A/MIGUEL,MARCELO,1619,ALASKA AVE,DALLAS,221795.0,95.0
126,LEXIAM PROPERTIES LLC,NaN,0,PO BOX 29566,DALLAS,342975.0,95.0
159,HIRLA DANIELA,MERCADO,3950,DEEP VALLEY DR,DALLAS,707891.0,95.0

In [334]:
top_20_highest

,Mortgagor First Name,Mortgagor Last Name,Owner Street Number,Owner Street Name,City Name,Estimated Equity,Estimated Margin percent
53,MARCUS D/COREY,FURLOUGH,1846,E LEDBETTER DR,DALLAS,246979.0,99.0
216,CAMIE,SANCHEZ ETAL,784,HALL RD,GARLAND,361484.0,99.0
261,DERRICK,BATTS,1935,RYDER DR,LANCASTER,266035.0,99.0
43,ANNIE,HUFF,1928,MATAGORDA DR,DALLAS,324675.0,99.0
7,WILFREDO PEREZ,MENDEZ ET AL,3813,FOREST LAWN RD,BALCH SPRINGS,155460.0,99.0
231,RODNEY,DE BAUN ETAL,4435,ARBOR LN,GRAND PRAIRIE,229515.0,98.0
58,ARTURO,GARCIA V,9905,HUSTEAD ST,DALLAS,207499.0,98.0
239,CARLOS/CHRISTINA,MORALES,4402,GREEN ACRES CT,GRAND PRAIRIE,218568.0,98.0
211,DAVID,ARCHULETA,2413,HIGH STAR DR,GARLAND,261278.0,98.0
106,KATHERINE/PETER,STANTON,7829,EL PENSADOR DR,DALLAS,483964.0,98.0
236,SANTIAGO,ZAMBRANO ETAL,626,AUSTIN ST,GRAND PRAIRIE,2148286.0,97.0
61,JAMES,JOHNSON,4446,CICERO ST,DALLAS,1141682.0,97.0
129,MIRIAN,FIERRO MEJIA ET AL,5007,BARTLETT AVE,DALLAS,129107.0,97.0
203,GLEN,BAILEY ETAL,1810,PATRICIA LN,GARLAND,269604.0,97.0
107,CASEY A,BATES,4721,BRADFORD DR UNIT 4721B,DALLAS,2656896.0,96.0
12,TERRENCE G,ORR,1038,HAMPSHIRE LN,CEDAR HILL,317915.0,96.0
18,RUSSELL M/JAMITA J,MACHEN,1547,CYPRESS BEND DR,CEDAR HILL,636526.0,96.0
57,MARIA A/MIGUEL,MARCELO,1619,ALASKA AVE,DALLAS,221795.0,95.0
126,LEXIAM PROPERTIES LLC,NaN,0,PO BOX 29566,DALLAS,342975.0,95.0
159,HIRLA DANIELA,MERCADO,3950,DEEP VALLEY DR,DALLAS,707891.0,95.0

In [335]:
dfrev1.columns

Index(['Mortgagor First Name', 'Mortgagor Last Name', 'Owner Street Number',
       'Owner Street Name', 'City Name', 'Estimated Equity',
       'Estimated Margin percent'],
      dtype='object')

In [336]:
# these chnges will effect the dfrev1, there is no need to attempt it on dfrev1

df.rename(
    columns = {
        'Mortgagor First Name':'First Name', 
        'Mortgagor Last Name':'Last Name',
        'Owner Street Number':'Adress Num',
        'Owner Street Name':'Street Name',
        'City Name':'City',
        'Estimated Equity':'Est. Equity',
        'Estimated Margin percent':'Est. Margin %',
    },
    inplace=True)

In [337]:
dfrev1

,Mortgagor First Name,Mortgagor Last Name,Owner Street Number,Owner Street Name,City Name,Estimated Equity,Estimated Margin percent
0,DEANNA,PERKINS,17073,PLANTERS ROW,ADDISON,289574.0,75.0
1,MARC,HARPER,15848,BREEDLOVE PLACE #153,ADDISON,NaN,NaN
2,MICHAEL,BENJAMIN,15811,SPECTRUM DR # 176,ADDISON,NaN,NaN
3,KENDRICK D,ROSENDOLL,14718,BROADVIEW DR,BALCH SPRINGS,235426.0,69.0
4,ANDRES,DEL RIO TREJO,14910,MARSHA DR,BALCH SPRINGS,108425.0,48.0
...,...,...,...,...,...,...,...
293,NaN,WATER SPRING LLC,10206,LIBERTY GROVE RD,ROWLETT,NaN,NaN
294,THOMAS/BLESS,CHERRY,910,ARMSTRONG RD,SEAGOVILLE,74963.0,23.0
295,CARLOS E,VILLA,719,S GREAT SOUTHWEST PKWY APT 134,SEAGOVILLE,72023.0,24.0
296,DANIEL,HOLGUIN ETAL,100,COLONIAL CIR,SEAGOVILLE,239461.0,86.0
297,FERNANDO G,TRUJILLO,835,WIXOM LN,SUNNYVALE,60991.0,22.0

In [338]:
def has_ten_digit_number(df):
    """Checks if any column in a DataFrame contains a 10-digit number."""

    for col in df.columns:
        if df[col].astype(str).str.match(r'^\d{10}$').any():
            return True
    return False

# Example usage
df = pd.DataFrame({'A': [1234567890, 123], 'B': ['abc', 'def']})
print(has_ten_digit_number(df))

True

AttributeError: 'DataFrame' object has no attribute 'has_ten_digit_number'