In [3]:
import pandas as pd

In [9]:
csv = pd.read_csv("DFWNov.csv")

In [25]:
csv.head()

,Estimated Equity,Estimated Margin percent,Est Unpaid Bal,Clerk Number,Year of Report,Month of Report,City Name,County Code,Mapsco Page,Mapsco Section,...,Owner Street Name,Owner Zip,Owner City,Owner State,Tax ID,Status,OpeningBid,Auction Date,Georeference,Zillow URL
0,289574.0,75.0,96706,0,2024,12,ADDISON,DA,NaN,NaN,...,PLANTERS ROW,75001,ADDISON,TX,100006500B0160000,NaN,0,December,http://www.zillow.com/homes/17073-PLANTERS-ROW...,NaN
1,NaN,NaN,0,0,2024,12,ADDISON,DA,NaN,NaN,...,BREEDLOVE PLACE #153,75001,ADDISON,TX,10C05500001700153,NaN,0,December,http://www.zillow.com/homes/15848-BREEDLOVE-PL...,NaN
2,NaN,NaN,0,0,2024,12,ADDISON,DA,NaN,NaN,...,SPECTRUM DR # 176,75001,ADDISON,TX,10C05500002000176,NaN,0,December,http://www.zillow.com/homes/15811-SPECTRUM-DR-...,NaN
3,235426.0,69.0,107444,0,2024,12,BALCH SPRINGS,DA,NaN,NaN,...,BROADVIEW DR,75180,BALCH SPRINGS,TX,120798000M0240000,NaN,0,December,http://www.zillow.com/homes/14718-BROADVIEW-DR...,NaN
4,108425.0,48.0,115535,0,2024,12,BALCH SPRINGS,DA,NaN,NaN,...,MARSHA DR,75180,BALCH SPRINGS,TX,12077500050260000,NaN,0,December,http://www.zillow.com/homes/14910-MARSHA-DR-N_rb/,NaN

In [31]:
print(csv.columns.tolist())

['Estimated Equity', 'Estimated Margin percent', 'Est Unpaid Bal', 'Clerk Number', 'Year of Report', 'Month of Report', 'City Name', 'County Code', 'Mapsco Page', 'Mapsco Section', 'Class', 'Loan Type', 'Street Number', 'Address', 'B/B/G', 'Property Sq Footage', 'Pool', 'Zip', 'Legal Description 1', 'Legal Description 2', 'Subdivision', 'Mortgagor First Name', 'Mortgagor Last Name', 'Mortgagee', 'Trustee', 'Auction Sale Time', 'Volume', 'Page', 'Loan Month', 'Loan Year', 'Original Loan Amount', 'Monthly Payment', 'Interest Rate', 'Loan Expires Month', 'Loan Expires Year', 'Year Of Construction', 'Assessed Value', 'City Code', 'Number of Units', 'Previous Posting', 'Comment', 'Owner Street Number', 'Owner Street Name', 'Owner Zip', 'Owner City', 'Owner State', 'Tax ID', 'Status', 'OpeningBid', 'Auction Date', 'Georeference', 'Zillow URL']

In [33]:
Owner_Name=csv[['Mortgagor First Name'] + ['Mortgagor Last Name']]

In [35]:
print(Owner_Name)

    Mortgagor First Name Mortgagor Last Name
0                 DEANNA             PERKINS
1                   MARC              HARPER
2                MICHAEL            BENJAMIN
3            KENDRICK  D           ROSENDOLL
4                 ANDRES       DEL RIO TREJO
..                   ...                 ...
293                  NaN    WATER SPRING LLC
294         THOMAS/BLESS              CHERRY
295             CARLOS E               VILLA
296               DANIEL        HOLGUIN ETAL
297           FERNANDO G            TRUJILLO

[298 rows x 2 columns]

In [326]:
Address = csv[['Street Number'] + ['Address'] + ['City Name'] + ['Owner State'] + ['Zip']]
Address

    Street Number               Address      City Name Owner State    Zip
0           17073          PLANTERS ROW        ADDISON          TX  75001
1           15848  BREEDLOVE PLACE #153        ADDISON          TX  75001
2           15811     SPECTRUM DR # 176        ADDISON          TX  75001
3           14718          BROADVIEW DR  BALCH SPRINGS          TX  75180
4           14910             MARSHA DR  BALCH SPRINGS          TX  75180
..            ...                   ...            ...         ...    ...
293         10206      LIBERTY GROVE RD        ROWLETT          TX  75089
294           910          ARMSTRONG RD     SEAGOVILLE          TX  75159
295           531               JUDY LN     SEAGOVILLE          TX  75159
296           100       COLONIAL CIRCLE     SEAGOVILLE          TX  75159
297           541              POLLY RD      SUNNYVALE          TX  75182

[298 rows x 5 columns]

In [350]:
Owner_Name
Address

    Street Number               Address      City Name Owner State    Zip
0           17073          PLANTERS ROW        ADDISON          TX  75001
1           15848  BREEDLOVE PLACE #153        ADDISON          TX  75001
2           15811     SPECTRUM DR # 176        ADDISON          TX  75001
3           14718          BROADVIEW DR  BALCH SPRINGS          TX  75180
4           14910             MARSHA DR  BALCH SPRINGS          TX  75180
..            ...                   ...            ...         ...    ...
293         10206      LIBERTY GROVE RD        ROWLETT          TX  75089
294           910          ARMSTRONG RD     SEAGOVILLE          TX  75159
295           531               JUDY LN     SEAGOVILLE          TX  75159
296           100       COLONIAL CIRCLE     SEAGOVILLE          TX  75159
297           541              POLLY RD      SUNNYVALE          TX  75182

[298 rows x 5 columns]

In [243]:
Fast_Stats = csv[['Estimated Equity']+ ['Estimated Margin percent']+ ['Est Unpaid Bal']+ ['Loan Year']+ ['Original Loan Amount']+ ['Monthly Payment']+ ['Interest Rate']]

In [451]:
Fast_Stats

,Estimated Equity,Estimated Margin percent,Est Unpaid Bal,Loan Year,Original Loan Amount,Monthly Payment,Interest Rate
0,289574.0,75.0,96706,2008,147200,0,0.00
1,NaN,NaN,0,0,0,0,0.00
2,NaN,NaN,0,0,0,0,0.00
3,235426.0,69.0,107444,2010,148993,789,4.87
4,108425.0,48.0,115535,2017,129609,677,4.75
...,...,...,...,...,...,...,...
293,NaN,NaN,0,2022,3797000,0,0.00
294,74963.0,23.0,246587,2021,265109,1077,2.71
295,72023.0,24.0,222307,2021,230743,0,0.00
296,239461.0,86.0,37699,2003,80900,0,0.00
297,60991.0,22.0,212429,2022,233000,1778,4.52

In [429]:
Big_Equity = csv[csv['Estimated Equity']>20000]
Full_Name = DFW_Big_Equity_Info['Full Name']

In [249]:
Big_Equity.shape

(234, 52)

In [251]:
Big_Equity.head(52)

,Estimated Equity,Estimated Margin percent,Est Unpaid Bal,Clerk Number,Year of Report,Month of Report,City Name,County Code,Mapsco Page,Mapsco Section,...,Owner Street Name,Owner Zip,Owner City,Owner State,Tax ID,Status,OpeningBid,Auction Date,Georeference,Zillow URL
0,289574.0,75.0,96706,0,2024,12,ADDISON,DA,NaN,NaN,...,PLANTERS ROW,75001,ADDISON,TX,100006500B0160000,NaN,0,December,http://www.zillow.com/homes/17073-PLANTERS-ROW...,NaN
3,235426.0,69.0,107444,0,2024,12,BALCH SPRINGS,DA,NaN,NaN,...,BROADVIEW DR,75180,BALCH SPRINGS,TX,120798000M0240000,NaN,0,December,http://www.zillow.com/homes/14718-BROADVIEW-DR...,NaN
4,108425.0,48.0,115535,0,2024,12,BALCH SPRINGS,DA,NaN,NaN,...,MARSHA DR,75180,BALCH SPRINGS,TX,12077500050260000,NaN,0,December,http://www.zillow.com/homes/14910-MARSHA-DR-N_rb/,NaN
5,183425.0,88.0,24915,0,2024,12,BALCH SPRINGS,DA,NaN,NaN,...,PATTI LN,75180,BALCH SPRINGS,TX,12048500000200000,NaN,0,December,http://www.zillow.com/homes/11220-PATTI-LN-N_rb/,NaN
6,92989.0,44.0,120261,0,2024,12,BALCH SPRINGS,DA,NaN,NaN,...,MOHAWK DR,75180,BALCH SPRINGS,TX,12071500070020000,NaN,0,December,http://www.zillow.com/homes/4324-MOHAWK-DR-N_rb/,NaN
7,155460.0,99.0,1890,30,2024,12,BALCH SPRINGS,DA,NaN,NaN,...,FOREST LAWN RD,75180,BALCH SPRINGS,TX,12050500060050000,NaN,0,December,http://www.zillow.com/homes/3813-FOREST-LAWN-R...,NaN
8,122587.0,27.0,332223,0,2024,12,CARROLLTON,DA,NaN,NaN,...,KIMBERLY CT,75075,PLANO,TX,14034900010070000,NaN,0,December,http://www.zillow.com/homes/2221-CRISTINA-CIR-...,NaN
9,278611.0,77.0,82509,0,2024,12,CARROLLTON,DA,NaN,NaN,...,ROSEWOOD PL,75006,CARROLLTON,TX,14016700010080000,NaN,0,December,http://www.zillow.com/homes/1012-ROSEWOOD-PL-P...,NaN
10,253089.0,82.0,57191,0,2024,12,CEDAR HILL,DA,NaN,NaN,...,S CARRIER PKWY APT 902,75052,GRAND PRAIRIE,TX,160426837A02R0000,NaN,0,December,http://www.zillow.com/homes/609-THORTON-CT-N_rb/,NaN
11,241103.0,86.0,38337,0,2024,12,CEDAR HILL,DA,NaN,NaN,...,WITHERSPOON CT,75104,CEDAR HILL,TX,160425500L0300000,NaN,0,December,http://www.zillow.com/homes/825-WITHERSPOON-CT...,NaN
12,317915.0,96.0,12725,0,2024,12,CEDAR HILL,DA,NaN,NaN,...,HAMPSHIRE LN,75104,CEDAR HILL,TX,160324000C0280000,NaN,0,December,http://www.zillow.com/homes/1038-HAMPSHIRE-LN-...,NaN
13,260528.0,81.0,61062,0,2024,12,CEDAR HILL,DA,NaN,NaN,...,RED OAK TRAILS,75104,CEDAR HILL,TX,160128500E0180000,NaN,0,December,http://www.zillow.com/homes/908-RED-OAK-TRAILS...,NaN
14,334420.0,90.0,37360,0,2024,12,CEDAR HILL,DA,NaN,NaN,...,SUMMERS DR,75104,CEDAR HILL,TX,16005910050130000,NaN,0,December,http://www.zillow.com/homes/1544-SUMMERS-DR-N_rb/,NaN
15,276332.0,84.0,51478,0,2024,12,CEDAR HILL,DA,NaN,NaN,...,JAMES ST,75104,CEDAR HILL,TX,16042810060090000,NaN,0,December,http://www.zillow.com/homes/1401-JAMES-ST-N_rb/,NaN
16,234350.0,40.0,349650,0,2024,12,CEDAR HILL,DA,NaN,NaN,...,E WINTERGREEN RD,75104,CEDAR HILL,TX,16048500010050000,NaN,0,December,http://www.zillow.com/homes/1021-E-WINTERGREEN...,NaN
17,209781.0,44.0,268139,0,2024,12,CEDAR HILL,DA,NaN,NaN,...,PORT PHILLIP DR,76002,ARLINGTON,TX,16038000020040000,NaN,0,December,http://www.zillow.com/homes/909-HICKORY-KNOB-C...,NaN
18,636526.0,96.0,25464,0,2024,12,CEDAR HILL,DA,NaN,NaN,...,CYPRESS BEND DR,75104,CEDAR HILL,TX,16027970004170000,NaN,0,December,http://www.zillow.com/homes/1547-CYPRESS-BEND-...,NaN
19,362096.0,70.0,156924,0,2024,12,COPPELL,DA,NaN,NaN,...,ASHLEY DR,75019,COPPELL,TX,180063500H0030000,NaN,0,December,http://www.zillow.com/homes/335-ASHLEY-DR-N_rb/,NaN
20,308274.0,75.0,103236,0,2024,12,COPPELL,DA,NaN,NaN,...,ST ANDREWS PL,75019,COPPELL,TX,180068700C0140000,NaN,0,December,http://www.zillow.com/homes/611-ST-ANDREWS-PL-...,NaN
21,230166.0,80.0,58834,0,2024,12,COPPELL,DA,NaN,NaN,...,NIXON ST,75019,COPPELL,TX,18005560040370000,NaN,0,December,http://www.zillow.com/homes/232-NIXON-ST-N_rb/,NaN
22,282460.0,87.0,43000,0,2024,12,DALLAS,DA,NaN,NaN,...,WEST RIM RD,75211,DALLAS,TX,00767100110270000,NaN,0,December,http://www.zillow.com/homes/1471-WEST-RIM-RD-N...,NaN
23,34680.0,13.0,224730,0,2024,12,DALLAS,DA,NaN,NaN,...,MARSHALL DR,75210,DALLAS,TX,00000179623000000,NaN,0,December,http://www.zillow.com/homes/4011-MARSHALL-DR-N...,NaN
24,213386.0,94.0,12774,0,2024,12,DALLAS,DA,NaN,NaN,...,RIDGEWICK DR,75217,DALLAS,TX,00000556318000000,NaN,0,December,http://www.zillow.com/homes/7502-RIDGEWICK-DR-...,NaN
25,94038.0,14.0,568242,0,2024,12,DALLAS,DA,NaN,NaN,...,E AIRPORT FWY STE 370,75062,IRVING,TX,00000703609000100,NaN,0,December,http://www.zillow.com/homes/2419-CROSSMAN-AVE-...,NaN
27,68953.0,45.0,84497,0,2024,12,DALLAS,DA,NaN,NaN,...,ALLEN ST PMB 2046,75204,DALLAS,TX,00000175663000000,NaN,0,December,http://www.zillow.com/homes/4607-SPRING-GARDEN...,NaN
28,561630.0,54.0,480630,0,2024,12,DALLAS,DA,NaN,NaN,...,MELROSE AVE,75206,DALLAS,TX,00000188014000100,NaN,0,December,http://www.zillow.com/homes/5415-MELROSE-AVE-_rb/,NaN
30,109719.0,37.0,186031,0,2024,12,DALLAS,DA,NaN,NaN,...,RIATA LN,75253,DALLAS,TX,00881300F0010000,NaN,0,December,http://www.zillow.com/homes/14203-RIATA-LN-N_rb/,NaN
31,322418.0,86.0,51552,0,2024,12,DALLAS,DA,NaN,NaN,...,W FIVE MILE PKWY,75233,DALLAS,TX,00000491164000000,NaN,0,December,http://www.zillow.com/homes/2542-W-FIVE-MILE-P...,NaN
32,124068.0,64.0,68632,0,2024,12,DALLAS,DA,NaN,NaN,...,PRAIRIE VIEW DR,75235,DALLAS,TX,00000776950000000,NaN,0,December,http://www.zillow.com/homes/1915-PRAIRIE-VIEW-...,NaN
33,178698.0,82.0,38582,0,2024,12,DALLAS,DA,NaN,NaN,...,GLENCLIFF DR,75217,DALLAS,TX,00669600040320000,NaN,0,December,http://www.zillow.com/homes/1314-GLENCLIFF-DR-...,NaN
34,589996.0,82.0,131414,0,2024,12,DALLAS,DA,NaN,NaN,...,ALTA VISTA LN,75229,DALLAS,TX,00000584152000000,NaN,0,December,http://www.zillow.com/homes/3959-ALTA-VISTA-LN...,NaN
35,95105.0,38.0,152475,0,2024,12,DALLAS,DA,NaN,NaN,...,HEDGE DR,75249,DALLAS,TX,00000820902480000,NaN,0,December,http://www.zillow.com/homes/7102-HEDGE-DR-N_rb/,NaN
36,456725.0,84.0,89705,0,2024,12,DALLAS,DA,NaN,NaN,...,LANSHIRE DR,75238,DALLAS,TX,00000736066000000,NaN,0,December,http://www.zillow.com/homes/9844-LANSHIRE-DR-N...,NaN
37,122463.0,38.0,199277,0,2024,12,DALLAS,DA,NaN,NaN,...,CUSHING DR,75217,DALLAS,TX,00778900060030000,NaN,0,December,http://www.zillow.com/homes/10106-CUSHING-DR-N...,NaN
38,121122.0,46.0,142978,0,2024,12,DALLAS,DA,NaN,NaN,...,NEBRASKA AVE,75216,DALLAS,TX,00000478138000000,NaN,0,December,http://www.zillow.com/homes/3307-NEBRASKA-AVE-...,NaN
42,176707.0,67.0,87143,0,2024,12,DALLAS,DA,NaN,NaN,...,GREAT LIGHT DR,75228,DALLAS,TX,007364000D0230000,NaN,0,December,http://www.zillow.com/homes/2339-GREAT-LIGHT-D...,NaN
43,324675.0,99.0,4305,0,2024,12,DALLAS,DA,NaN,NaN,...,MATAGORDA DR,75232,DALLAS,TX,00000651547000000,NaN,0,December,http://www.zillow.com/homes/1928-MATAGORDA-DR-...,NaN
44,271023.0,94.0,18787,0,2024,12,DALLAS,DA,NaN,NaN,...,CHINABERRY RD,75249,DALLAS,TX,00000820820420000,NaN,0,December,http://www.zillow.com/homes/7119-CHINABERRY-RD...,NaN
45,59446.0,20.0,234734,0,2024,12,DALLAS,DA,NaN,NaN,...,SANDRA LYNN DR,75228,DALLAS,TX,00000716455000000,NaN,0,December,http://www.zillow.com/homes/10335-SANDRA-LYNN-...,NaN
46,140466.0,45.0,170254,0,2024,12,DALLAS,DA,NaN,NaN,...,E RED BIRD LN,75241,DALLAS,TX,00000646855000000,NaN,0,December,http://www.zillow.com/homes/1533-E-RED-BIRD-LN...,NaN
47,162753.0,74.0,57097,0,2024,12,DALLAS,DA,NaN,NaN,...,BERRIDGE LN,75227,DALLAS,TX,006127HH000320000,NaN,0,December,http://www.zillow.com/homes/4912-BERRIDGE-LN-N...,NaN
48,245984.0,43.0,330466,0,2024,12,DALLAS,DA,NaN,NaN,...,PATIENCE BLVD,75236,DALLAS,TX,008710000T0030000,NaN,0,December,http://www.zillow.com/homes/3515-PATIENCE-BLVD...,NaN
49,161993.0,63.0,96087,0,2024,12,DALLAS,DA,NaN,NaN,...,MANHATTAN BEACH BLVD,90278,REDONDO BEACH,CA,00000608641000000,NaN,0,December,http://www.zillow.com/homes/2959-DOTHAN-LN-N_rb/,NaN
50,187008.0,83.0,39532,0,2024,12,DALLAS,DA,NaN,NaN,...,HARLANDALE AVE,75216,DALLAS,TX,00000270256000000,NaN,0,December,http://www.zillow.com/homes/1235-HARLANDALE-AV...,NaN
51,216170.0,76.0,68090,0,2024,12,DALLAS,DA,NaN,NaN,...,HUNTERS RIDGE DR,75248,DALLAS,TX,00829400210380000,NaN,0,December,http://www.zillow.com/homes/6213-BALCONY-LN-N_rb/,NaN
52,222501.0,80.0,54689,0,2024,12,DALLAS,DA,NaN,NaN,...,CALLE DEL ORO LN,75217,DALLAS,TX,007801000A0210000,NaN,0,December,http://www.zillow.com/homes/9720-CALLE-DEL-ORO...,NaN
53,246979.0,99.0,3051,0,2024,12,DALLAS,DA,NaN,NaN,...,E LEDBETTER DR,75216,DALLAS,TX,00000319837000000,NaN,0,December,http://www.zillow.com/homes/1846-E-LEDBETTER-D...,NaN
54,371066.0,50.0,377664,0,2024,12,DALLAS,DA,NaN,NaN,...,DEEP VALLEY DR,75244,DALLAS,TX,00000583123000000,NaN,0,December,http://www.zillow.com/homes/3950-DEEP-VALLEY-D...,NaN
55,52580.0,36.0,92000,0,2024,12,DALLAS,DA,NaN,NaN,...,YORK ST,75210,DALLAS,TX,00000201436000000,NaN,0,December,http://www.zillow.com/homes/3607-YORK-ST-N_rb/,NaN
56,265687.0,77.0,79383,0,2024,12,DALLAS,DA,NaN,NaN,...,LIGHT POINTE DR,75228,DALLAS,TX,007364000A0150000,NaN,0,December,http://www.zillow.com/homes/3327-LIGHT-POINTE-...,NaN
57,221795.0,95.0,11955,0,2024,12,DALLAS,DA,NaN,NaN,...,ALASKA AVE,75216,DALLAS,TX,00000281572000000,NaN,0,December,http://www.zillow.com/homes/1619-ALASKA-AVE-N_rb/,NaN
58,207499.0,98.0,3351,0,2024,12,DALLAS,DA,NaN,NaN,...,HUSTEAD ST,75217,DALLAS,TX,00671100090030000,NaN,0,December,http://www.zillow.com/homes/9905-HUSTEAD-ST-N_rb/,NaN

In [253]:
Dallas = Big_Equity[csv['City Name']=='DALLAS']

C:\Users\admin\AppData\Local\Temp\ipykernel_18324\1220280634.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  Dallas = Big_Equity[csv['City Name']=='DALLAS']

In [255]:
Dallas.head(5)

,Estimated Equity,Estimated Margin percent,Est Unpaid Bal,Clerk Number,Year of Report,Month of Report,City Name,County Code,Mapsco Page,Mapsco Section,...,Owner Street Name,Owner Zip,Owner City,Owner State,Tax ID,Status,OpeningBid,Auction Date,Georeference,Zillow URL
22,282460.0,87.0,43000,0,2024,12,DALLAS,DA,NaN,NaN,...,WEST RIM RD,75211,DALLAS,TX,00767100110270000,NaN,0,December,http://www.zillow.com/homes/1471-WEST-RIM-RD-N...,NaN
23,34680.0,13.0,224730,0,2024,12,DALLAS,DA,NaN,NaN,...,MARSHALL DR,75210,DALLAS,TX,00000179623000000,NaN,0,December,http://www.zillow.com/homes/4011-MARSHALL-DR-N...,NaN
24,213386.0,94.0,12774,0,2024,12,DALLAS,DA,NaN,NaN,...,RIDGEWICK DR,75217,DALLAS,TX,00000556318000000,NaN,0,December,http://www.zillow.com/homes/7502-RIDGEWICK-DR-...,NaN
25,94038.0,14.0,568242,0,2024,12,DALLAS,DA,NaN,NaN,...,E AIRPORT FWY STE 370,75062,IRVING,TX,00000703609000100,NaN,0,December,http://www.zillow.com/homes/2419-CROSSMAN-AVE-...,NaN
27,68953.0,45.0,84497,0,2024,12,DALLAS,DA,NaN,NaN,...,ALLEN ST PMB 2046,75204,DALLAS,TX,00000175663000000,NaN,0,December,http://www.zillow.com/homes/4607-SPRING-GARDEN...,NaN

In [257]:
Big_Equity.iloc[9:25, 42:45]

        Owner Street Name  Owner Zip  Owner City
11         WITHERSPOON CT      75104  CEDAR HILL
12           HAMPSHIRE LN      75104  CEDAR HILL
13         RED OAK TRAILS      75104  CEDAR HILL
14             SUMMERS DR      75104  CEDAR HILL
15               JAMES ST      75104  CEDAR HILL
16       E WINTERGREEN RD      75104  CEDAR HILL
17        PORT PHILLIP DR      76002   ARLINGTON
18        CYPRESS BEND DR      75104  CEDAR HILL
19              ASHLEY DR      75019     COPPELL
20          ST ANDREWS PL      75019     COPPELL
21               NIXON ST      75019     COPPELL
22            WEST RIM RD      75211      DALLAS
23            MARSHALL DR      75210      DALLAS
24           RIDGEWICK DR      75217      DALLAS
25  E AIRPORT FWY STE 370      75062      IRVING
27      ALLEN ST PMB 2046      75204      DALLAS

In [259]:
Big_Equity.sort_values(by='Estimated Equity').tail()

,Estimated Equity,Estimated Margin percent,Est Unpaid Bal,Clerk Number,Year of Report,Month of Report,City Name,County Code,Mapsco Page,Mapsco Section,...,Owner Street Name,Owner Zip,Owner City,Owner State,Tax ID,Status,OpeningBid,Auction Date,Georeference,Zillow URL
117,1117819.0,67.0,562211,13,2024,12,DALLAS,DA,NaN,NaN,...,BRETTON WOODS,75220,DALLAS,TX,00557300030060000,NaN,0,December,http://www.zillow.com/homes/11-BRETTON-WOODS-W...,NaN
61,1141682.0,97.0,38598,0,2024,12,DALLAS,DA,NaN,NaN,...,CICERO ST,75216,DALLAS,TX,0068400010010000,NaN,0,December,http://www.zillow.com/homes/4446-CICERO-ST-N_rb/,NaN
236,2148286.0,97.0,64654,0,2024,12,GRAND PRAIRIE,DA,NaN,NaN,...,AUSTIN ST,75051,GRAND PRAIRIE,TX,28253500010170000,NaN,0,December,http://www.zillow.com/homes/626-AUSTIN-ST-N_rb/,NaN
144,2278908.0,50.0,2307782,9,2024,12,DALLAS,DA,NaN,NaN,...,MERIDIAN AVE APT 707,33139,MIAMI BEACH,FL,0060350A000090000,NaN,0,December,http://www.zillow.com/homes/3435-S-POLK-ST-P_rb/,NaN
107,2656896.0,96.0,103184,0,2024,12,DALLAS,DA,NaN,NaN,...,BRADFORD DR UNIT 4721B,75219,DALLAS,TX,00C4735000024721B,NaN,0,December,http://www.zillow.com/homes/4721-BRADFORD-DR-U...,NaN

In [261]:
Big_Equity= Big_Equity.drop(['Clerk Number','Year of Report','Month of Report','County Code','Mapsco Page','Status','OpeningBid','Auction Date','Zillow URL'], axis=1)

In [263]:
Big_Equity.sort_values(by='Estimated Equity').tail()

,Estimated Equity,Estimated Margin percent,Est Unpaid Bal,City Name,Mapsco Section,Class,Loan Type,Street Number,Address,B/B/G,...,Number of Units,Previous Posting,Comment,Owner Street Number,Owner Street Name,Owner Zip,Owner City,Owner State,Tax ID,Georeference
117,1117819.0,67.0,562211,DALLAS,NaN,Single Family Residential,Conventional,11,BRETTON WOODS WAY,3/3/2,...,1,Y,NaN,11,BRETTON WOODS,75220,DALLAS,TX,00557300030060000,http://www.zillow.com/homes/11-BRETTON-WOODS-W...
61,1141682.0,97.0,38598,DALLAS,NaN,Single Family Residential,Conventional,4446,CICERO ST,3/1/1,...,1,NaN,NaN,4446,CICERO ST,75216,DALLAS,TX,0068400010010000,http://www.zillow.com/homes/4446-CICERO-ST-N_rb/
236,2148286.0,97.0,64654,GRAND PRAIRIE,NaN,Single Family Residential,FHA,626,AUSTIN ST,4/1/0,...,1,Y,NaN,626,AUSTIN ST,75051,GRAND PRAIRIE,TX,28253500010170000,http://www.zillow.com/homes/626-AUSTIN-ST-N_rb/
144,2278908.0,50.0,2307782,DALLAS,NaN,Multifamily,Commercial,3435,S POLK ST,0/0/0,...,1,NaN,NaN,1020,MERIDIAN AVE APT 707,33139,MIAMI BEACH,FL,0060350A000090000,http://www.zillow.com/homes/3435-S-POLK-ST-P_rb/
107,2656896.0,96.0,103184,DALLAS,NaN,Condominium,FANNIE MAE/FREDDIE MAC,4721,BRADFORD DR UNIT 4721B,2/1/0,...,1,Y,NaN,4721,BRADFORD DR UNIT 4721B,75219,DALLAS,TX,00C4735000024721B,http://www.zillow.com/homes/4721-BRADFORD-DR-U...

In [265]:
Big_Equity= Big_Equity.drop(['Mapsco Section','Georeference','Previous Posting','Comment',], axis=1)
Big_Equity.sort_values(by='Estimated Equity').tail()

,Estimated Equity,Estimated Margin percent,Est Unpaid Bal,City Name,Class,Loan Type,Street Number,Address,B/B/G,Property Sq Footage,...,Year Of Construction,Assessed Value,City Code,Number of Units,Owner Street Number,Owner Street Name,Owner Zip,Owner City,Owner State,Tax ID
117,1117819.0,67.0,562211,DALLAS,Single Family Residential,Conventional,11,BRETTON WOODS WAY,3/3/2,4949,...,2008,1680030,DALLAS,1,11,BRETTON WOODS,75220,DALLAS,TX,00557300030060000
61,1141682.0,97.0,38598,DALLAS,Single Family Residential,Conventional,4446,CICERO ST,3/1/1,1064,...,1940,1180280,DALLAS,1,4446,CICERO ST,75216,DALLAS,TX,0068400010010000
236,2148286.0,97.0,64654,GRAND PRAIRIE,Single Family Residential,FHA,626,AUSTIN ST,4/1/0,1596,...,1942,2212940,GRAND PRAIRIE,1,626,AUSTIN ST,75051,GRAND PRAIRIE,TX,28253500010170000
144,2278908.0,50.0,2307782,DALLAS,Multifamily,Commercial,3435,S POLK ST,0/0/0,37085,...,1973,4586690,DALLAS,1,1020,MERIDIAN AVE APT 707,33139,MIAMI BEACH,FL,0060350A000090000
107,2656896.0,96.0,103184,DALLAS,Condominium,FANNIE MAE/FREDDIE MAC,4721,BRADFORD DR UNIT 4721B,2/1/0,986,...,1955,2760080,DALLAS,1,4721,BRADFORD DR UNIT 4721B,75219,DALLAS,TX,00C4735000024721B

In [269]:
Big_Equity.sort_values(by='Estimated Equity').tail()

,,Estimated Equity,Estimated Margin percent,Est Unpaid Bal,City Name,Class,Loan Type,Street Number,Address,B/B/G,Property Sq Footage,...,Year Of Construction,Assessed Value,City Code,Number of Units,Owner Street Number,Owner Street Name,Owner Zip,Owner City,Owner State,Tax ID
Mortgagor First Name,Mortgagor Last Name,,,,,,,,,,,,,,,,,,,,,
KIM,PICHANICK ET AL,1117819.0,67.0,562211,DALLAS,Single Family Residential,Conventional,11,BRETTON WOODS WAY,3/3/2,4949,...,2008,1680030,DALLAS,1,11,BRETTON WOODS,75220,DALLAS,TX,00557300030060000
JAMES,JOHNSON,1141682.0,97.0,38598,DALLAS,Single Family Residential,Conventional,4446,CICERO ST,3/1/1,1064,...,1940,1180280,DALLAS,1,4446,CICERO ST,75216,DALLAS,TX,0068400010010000
SANTIAGO,ZAMBRANO ETAL,2148286.0,97.0,64654,GRAND PRAIRIE,Single Family Residential,FHA,626,AUSTIN ST,4/1/0,1596,...,1942,2212940,GRAND PRAIRIE,1,626,AUSTIN ST,75051,GRAND PRAIRIE,TX,28253500010170000
SPRING RIDGE POLK II INVESTMENT GROUP LLC,NaN,2278908.0,50.0,2307782,DALLAS,Multifamily,Commercial,3435,S POLK ST,0/0/0,37085,...,1973,4586690,DALLAS,1,1020,MERIDIAN AVE APT 707,33139,MIAMI BEACH,FL,0060350A000090000
CASEY A,BATES,2656896.0,96.0,103184,DALLAS,Condominium,FANNIE MAE/FREDDIE MAC,4721,BRADFORD DR UNIT 4721B,2/1/0,986,...,1955,2760080,DALLAS,1,4721,BRADFORD DR UNIT 4721B,75219,DALLAS,TX,00C4735000024721B

In [431]:
DFW_Big_Equity_Nov = pd.concat([Full_Name, Address, Fast_Stats], axis=1)

In [433]:
DFW_Big_Equity_Nov.tail()

,Full Name,Street Number,Address,City Name,Owner State,Zip,Estimated Equity,Estimated Margin percent,Est Unpaid Bal,Loan Year,Original Loan Amount,Monthly Payment,Interest Rate
285,NaN,2829,CLAY MATHIS RD,MESQUITE,TX,75181,NaN,NaN,0,2023,190000,0,6.09
287,GUANITA D/ARLUSTER WRIGHT JR ETAL,800,BRIDGEWATER LN,MESQUITE,TX,75181,NaN,NaN,0,1986,85738,0,0.00
291,MUSTAFA S BELLO,655,MATTHEW PL,RICHARDSON,TX,75081,NaN,NaN,0,2022,332000,0,5.00
292,PIERRE TURRELL,7941,CHAPMAN CIR,ROWLETT,TX,75089,NaN,NaN,0,0,0,0,0.00
293,NaN,10206,LIBERTY GROVE RD,ROWLETT,TX,75089,NaN,NaN,0,2022,3797000,0,0.00

In [435]:
DFW_Big_Equity_Nov= DFW_Big_Equity_Nov.fillna(0)

In [437]:
DFW_Big_Equity_Nov.tail(20)

,Full Name,Street Number,Address,City Name,Owner State,Zip,Estimated Equity,Estimated Margin percent,Est Unpaid Bal,Loan Year,Original Loan Amount,Monthly Payment,Interest Rate
139,JOHN P TERRY,5200,MARTEL AVE UNIT 20A,DALLAS,TX,75206,0.0,0.0,0,0,0,0,0.00
140,ALEXIUS CONROY,3210,CARLISLE ST UNIT 58,DALLAS,TX,75204,0.0,0.0,0,0,0,0,0.00
151,DUDLEY A DORT,5382,BOWSER AVE,DALLAS,TX,75209,0.0,0.0,0,0,0,0,0.00
158,JOHN R W FUGITT,1200,MAIN ST APT 204,DALLAS,TX,75202,0.0,0.0,0,0,0,0,0.00
169,JUANA I ROMERO ETAL,3110,WALNUT HILL LN,DALLAS,TX,75229,0.0,0.0,0,2022,200000,0,3.05
189,DAVID WHEATLEY,611,ORIOLE BLVD #703,DUNCANVILLE,TX,75116,0.0,0.0,0,0,0,0,0.00
210,BILLY H NGUYEN,4621,SPRUCEWOOD LN,GARLAND,TX,75044,0.0,0.0,0,2020,431000,0,0.00
213,LOIS J SIEBENTHALER,1221,RAVINA DR,GARLAND,TX,75041,0.0,0.0,0,2005,50000,0,5.00
217,0,217,BARGER ST,GARLAND,TX,75040,0.0,0.0,0,2023,16250,0,7.31
218,0,217,BARGER ST,GARLAND,TX,75040,0.0,0.0,0,2023,310500,0,7.31
220,STEPHEN LAM ETAL,3238,POTOMAC DR,GARLAND,NJ,75042,0.0,0.0,0,2018,4000000,0,4.50
249,LISA GRANT,2645,LOCKSLEY CHASE,IRVING,TX,75061,0.0,0.0,0,2024,300000,0,6.78
250,LIGIA BRINKMAN,330,LAS COLINAS BLVD #E-434,IRVING,TX,75039,0.0,0.0,0,0,0,0,0.00
278,COURTNEY CALIP,3104,SILVER CREEK DR,MESQUITE,TX,75181,0.0,0.0,0,0,0,0,0.00
281,JOE M RAMIREZ,1831,HIGHLAND ST,MESQUITE,TX,75149,0.0,0.0,0,2023,188000,0,6.78
285,0,2829,CLAY MATHIS RD,MESQUITE,TX,75181,0.0,0.0,0,2023,190000,0,6.09
287,GUANITA D/ARLUSTER WRIGHT JR ETAL,800,BRIDGEWATER LN,MESQUITE,TX,75181,0.0,0.0,0,1986,85738,0,0.00
291,MUSTAFA S BELLO,655,MATTHEW PL,RICHARDSON,TX,75081,0.0,0.0,0,2022,332000,0,5.00
292,PIERRE TURRELL,7941,CHAPMAN CIR,ROWLETT,TX,75089,0.0,0.0,0,0,0,0,0.00
293,0,10206,LIBERTY GROVE RD,ROWLETT,TX,75089,0.0,0.0,0,2022,3797000,0,0.00

In [453]:
DFW_Big_Equity_Nov_Equity = DFW_Big_Equity_Nov.sort_values(by='Estimated Equity', ascending=False)

print("\nSorted DataFrame (Highest to Lowest Estimated Equity Above $20,000):")
DFW_Big_Equity_Nov_Equity.head(60)

Sorted DataFrame (Highest to Lowest Estimated Equity Above $20,000):

,Full Name,Street Number,Address,City Name,Owner State,Zip,Estimated Equity,Estimated Margin percent,Est Unpaid Bal,Loan Year,Original Loan Amount,Monthly Payment,Interest Rate
107,CASEY A BATES,4721,BRADFORD DR UNIT 4721B,DALLAS,TX,75219,2656896.0,96.0,103184,2006,175417,0,6.75
144,0,3435,S POLK ST,DALLAS,FL,75224,2278908.0,50.0,2307782,2022,9319000,388673,3.89
236,SANTIAGO ZAMBRANO ETAL,626,AUSTIN ST,GRAND PRAIRIE,TX,75051,2148286.0,97.0,64654,2015,77569,360,3.75
61,JAMES JOHNSON,4446,CICERO ST,DALLAS,TX,75216,1141682.0,97.0,38598,2018,42000,200,3.95
117,KIM PICHANICK ET AL,11,BRETTON WOODS WAY,DALLAS,TX,75220,1117819.0,67.0,562211,2011,786250,3750,3.99
207,MICHAEL/YASMIN SUISSI,22,DUNROBIN,GARLAND,TX,75044,998772.0,74.0,354258,2007,576000,0,0.00
121,DAULTON/BERTHA CARO,6923,ROBIN RD,DALLAS,TX,75209,863507.0,92.0,72953,2013,127900,0,3.67
159,HIRLA DANIELA MERCADO,3950,DEEP VALLEY DR,DALLAS,TX,75244,707891.0,95.0,40839,2017,60400,0,0.00
96,KEVIN WILEY,4039,FAWNHOLLOW DR,DALLAS,TX,75244,685240.0,83.0,136640,2004,272000,0,0.00
109,NICHOLAS/AMY LEDGISTER,14208,HUGHES LN,DALLAS,TX,75254,674584.0,22.0,2384046,2022,2422500,15488,6.61
103,CARLEY R POTTS,9522,ALTA MIRA DR,DALLAS,TX,75218,662551.0,81.0,158539,2007,239100,1491,6.37
98,0,825,W PENTAGON PKWY,DALLAS,TX,75224,647094.0,46.0,753576,2020,915000,4257,4.50
18,RUSSELL M/JAMITA J MACHEN,1547,CYPRESS BEND DR,CEDAR HILL,TX,75104,636526.0,96.0,25464,2005,307500,0,0.00
34,GREG WOLFKIEL,3959,ALTA VISTA LN,DALLAS,TX,75229,589996.0,82.0,131414,2004,254840,0,0.00
70,KELLY M/JERRY W/JOSEPH W/KAY H DICKERSON,4515,HARVEST HILL RD,DALLAS,TX,75244,578658.0,72.0,221172,2013,280000,1426,4.54
94,TISHIA A/TIMOTHY B COX,6464,ELLSWORTH AVE,DALLAS,TX,75214,576048.0,67.0,277962,2006,468750,0,6.37
28,HALEY DEARMAN,5415,MELROSE AVE,DALLAS,TX,75206,561630.0,54.0,480630,2020,510400,0,0.00
71,RAJAN P PATEL,3920-22,TRAVIS ST UNIT 2,DALLAS,TX,75204,488164.0,90.0,54166,2001,150400,0,0.00
106,KATHERINE/PETER STANTON,7829,EL PENSADOR DR,DALLAS,TX,75248,483964.0,98.0,10136,2009,178000,0,5.24
36,JAMES W/LYNSEY PURL,9844,LANSHIRE DR,DALLAS,TX,75238,456725.0,84.0,89705,2005,160800,0,0.00
206,GONZALO MUNGUIA,2501,PECAN MEADOW DR,GARLAND,TX,75040,438053.0,83.0,86957,2005,158400,0,0.00
177,0,1702,CARRIAGE CREEK DR,DESOTO,TX,75115,424693.0,66.0,220187,2023,431000,0,6.81
193,FLORENTINO M SILVA ETAL,1742,PRESCOTT PL,FARMERS BRANCH,TX,75234,406019.0,45.0,491191,2019,529259,0,0.00
54,HIRLA D MERCADO,3950,DEEP VALLEY DR,DALLAS,TX,75244,371066.0,50.0,377664,2017,424000,0,3.86
19,MARCELA LEON,335,ASHLEY DR,COPPELL,TX,75019,362096.0,70.0,156924,2012,204232,0,0.00
216,CAMIE SANCHEZ ETAL,3114,MEDINA DR,GARLAND,TX,75041,361484.0,99.0,3186,2005,28200,0,0.00
126,0,13735,BIGGS ST,DALLAS,TX,75253,342975.0,95.0,16635,2012,131200,0,3.97
81,EMILY/MATTHEW REDDICK,4144,FLINTRIDGE DR,DALLAS,TX,75244,335796.0,61.0,211474,2015,263150,1231,3.83
14,ARAMINTA JOHNSON,1544,SUMMERS DR,CEDAR HILL,TX,75104,334420.0,90.0,37360,1999,131403,0,0.00
43,ANNIE HUFF,1928,MATAGORDA DR,DALLAS,TX,75232,324675.0,99.0,4305,1994,78937,0,0.00
31,MARIBEL CORONADO,2542,W FIVE MILE PKWY,DALLAS,TX,75233,322418.0,86.0,51552,2006,88000,0,0.00
12,TERRENCE G ORR,1038,HAMPSHIRE LN,CEDAR HILL,TX,75104,317915.0,96.0,12725,1996,110626,0,0.00
178,BRUCE JONES,1317,WOLF DR,DESOTO,TX,75115,313915.0,74.0,109985,2007,179900,0,0.00
20,JOHN/LEXIE C LEDBETTER,611,ST ANDREWS PL,COPPELL,TX,75019,308274.0,75.0,103236,2006,171000,0,0.00
179,EFFIE M BRYANT,1017,CLOVER DALE LN,DESOTO,TX,75115,307950.0,79.0,79590,2006,139650,0,0.00
196,JOHN /SANDRA GIVENS,1942,GARRISON WAY,GARLAND,TX,75040,305925.0,79.0,80425,2006,134320,0,0.00
234,KIMBERLY M ASTRAN,831,FAIR OAKS DR,GRAND PRAIRIE,TX,75052,304470.0,79.0,81760,2005,133192,824,6.29
93,GENEVIEVE BREMBRY,4209,BLACKHEATH RD,DALLAS,TX,75227,301178.0,84.0,57982,2003,120000,0,0.00
204,CALVIN L SANDERS,1925,CARTMAN RD,GARLAND,TX,75040,296658.0,81.0,69342,2003,150915,0,0.00
148,DENNIS JORDAN,1004,STAFFORD AVE,DALLAS,TX,75208,292170.0,39.0,460520,2020,500000,2082,2.90
0,DEANNA PERKINS,17073,PLANTERS ROW,ADDISON,TX,75001,289574.0,75.0,96706,2008,147200,0,0.00
185,S R MINSKY,602,LINKCREST CIR,DUNCANVILLE,TX,75137,288802.0,80.0,73228,2008,300000,1685,3.17
22,ANCELMO/MARIA L VASQUEZ,1471,WEST RIM RD,DALLAS,TX,75211,282460.0,87.0,43000,2002,99280,0,0.00
9,LAUREN M/ARRON J BOYLE,1012,ROSEWOOD PL,CARROLLTON,TX,75006,278611.0,77.0,82509,2007,120000,777,6.73
87,0,2375,SAINT FRANCIS AVE,DALLAS,TX,75228,278448.0,67.0,134252,2022,260000,22491,6.95
268,BELINDA K SOULES,605,VIA DEL SUR,MESQUITE,TX,75150,278420.0,78.0,78700,2009,111443,627,5.41
272,JOCQUNETTE/BRANDON PLUMMER,3204,SILVER CREEK DR,MESQUITE,TX,75181,277542.0,69.0,122668,2007,181068,1118,6.27
191,FIDELIA J MOORE ETAL,931,CLINT SMITH DR,DUNCANVILLE,TX,75137,276541.0,71.0,112479,2011,150482,0,0.00
15,STEPHANIE SHEFFIELD ETAL,1401,JAMES ST,CEDAR HILL,TX,75104,276332.0,84.0,51478,2002,118044,0,0.00
255,JAMES M ROBERTS,133,NORTH CREST ST,LANCASTER,TX,75146,274549.0,77.0,80691,2015,93362,0,0.00
176,0,1401,THISTLEWOOD DR,DESOTO,TX,75115,272266.0,69.0,120964,2021,235000,0,0.00
283,JOEL PATTERSON,306,EAST KIMBROUGH ST,MESQUITE,FL,75149,272102.0,87.0,42188,2003,86400,0,0.00
95,DEBORAH WILLIAMS,5985,HARBOR GLEN DR,DALLAS,TX,75249,271329.0,79.0,73691,2006,109600,767,7.50
44,ALFONZO WADE ETAL,7119,CHINABERRY RD,DALLAS,TX,75249,271023.0,94.0,18787,1998,71217,0,2.70
203,GLEN BAILEY ETAL,1810,PATRICIA LN,GARLAND,TX,75042,269604.0,97.0,9196,1996,82873,0,0.00
223,KELVIN M/MICHIEAL GASTON,501,CORAL REEF LN,GLENN HEIGHTS,TX,75154,267052.0,73.0,99318,2007,159200,0,6.69
245,JACK SHASTID ETAL,1104,SHUFFORD ST,IRVING,TX,75060,266519.0,83.0,54361,2004,105600,0,0.00
100,ORSON B EDMOND,7319,LOST CANYON DR,DALLAS,TX,75249,266514.0,84.0,50966,2005,93600,0,0.00
261,DERRICK BATTS,1935,RYDER DR,LANCASTER,TX,75146,266035.0,99.0,2915,2006,23060,0,6.62
56,TRACIE L WILLIAMS ETAL,3327,LIGHT POINTE DR,DALLAS,TX,75228,265687.0,77.0,79383,2012,105040,517,4.25

In [445]:
DFW_Big_Equity_Info = pd.concat([Full_Name, Address, Fast_Stats], axis=1)
DFW_Big_Equity_Info = DFW_Big_Equity_Info.sort_values(by='Estimated Margin percent', ascending=False)
print("""DFW Prospects sorted by \033[1m'Estimated Margin Percentage'\033[0m:""")
DFW_Big_Equity_Info.head(60)

DFW Prospects sorted by 'Estimated Margin Percentage':

,Full Name,Street Number,Address,City Name,Owner State,Zip,Estimated Equity,Estimated Margin percent,Est Unpaid Bal,Loan Year,Original Loan Amount,Monthly Payment,Interest Rate
53,MARCUS D/COREY FURLOUGH,1846,E LEDBETTER DR,DALLAS,TX,75216,246979.0,99.0,3051,1993,40000,0,0.00
43,ANNIE HUFF,1928,MATAGORDA DR,DALLAS,TX,75232,324675.0,99.0,4305,1994,78937,0,0.00
7,WILFREDO PEREZ MENDEZ ET AL,3813,FOREST LAWN RD,BALCH SPRINGS,TX,75180,155460.0,99.0,1890,2016,0,1,0.00
216,CAMIE SANCHEZ ETAL,3114,MEDINA DR,GARLAND,TX,75041,361484.0,99.0,3186,2005,28200,0,0.00
261,DERRICK BATTS,1935,RYDER DR,LANCASTER,TX,75146,266035.0,99.0,2915,2006,23060,0,6.62
58,ARTURO GARCIA V,9905,HUSTEAD ST,DALLAS,TX,75217,207499.0,98.0,3351,1988,51719,0,0.00
239,CARLOS/CHRISTINA MORALES,1113,SHAWNEE TRACE,GRAND PRAIRIE,TX,75051,218568.0,98.0,5102,2006,68000,0,6.13
211,DAVID ARCHULETA,2413,HIGH STAR DR,GARLAND,TX,75041,261278.0,98.0,5242,2005,74395,0,0.00
106,KATHERINE/PETER STANTON,7829,EL PENSADOR DR,DALLAS,TX,75248,483964.0,98.0,10136,2009,178000,0,5.24
231,RODNEY DE BAUN ETAL,625,BEECHWOOD DR,GRAND PRAIRIE,TX,75052,229515.0,98.0,4255,1988,72638,0,0.00
236,SANTIAGO ZAMBRANO ETAL,626,AUSTIN ST,GRAND PRAIRIE,TX,75051,2148286.0,97.0,64654,2015,77569,360,3.75
61,JAMES JOHNSON,4446,CICERO ST,DALLAS,TX,75216,1141682.0,97.0,38598,2018,42000,200,3.95
129,MIRIAN FIERRO MEJIA ET AL,5007,BARTLETT AVE,DALLAS,TX,75216,129107.0,97.0,3663,2014,28000,285,4.10
203,GLEN BAILEY ETAL,1810,PATRICIA LN,GARLAND,TX,75042,269604.0,97.0,9196,1996,82873,0,0.00
18,RUSSELL M/JAMITA J MACHEN,1547,CYPRESS BEND DR,CEDAR HILL,TX,75104,636526.0,96.0,25464,2005,307500,0,0.00
12,TERRENCE G ORR,1038,HAMPSHIRE LN,CEDAR HILL,TX,75104,317915.0,96.0,12725,1996,110626,0,0.00
107,CASEY A BATES,4721,BRADFORD DR UNIT 4721B,DALLAS,TX,75219,2656896.0,96.0,103184,2006,175417,0,6.75
126,NaN,13735,BIGGS ST,DALLAS,TX,75253,342975.0,95.0,16635,2012,131200,0,3.97
159,HIRLA DANIELA MERCADO,3950,DEEP VALLEY DR,DALLAS,TX,75244,707891.0,95.0,40839,2017,60400,0,0.00
57,MARIA A/MIGUEL MARCELO,1619,ALASKA AVE,DALLAS,TX,75216,221795.0,95.0,11955,1998,50358,0,0.00
24,KUMESHA JACKSON,7502,RIDGEWICK DR,DALLAS,TX,75217,213386.0,94.0,12774,1999,39750,0,0.00
44,ALFONZO WADE ETAL,7119,CHINABERRY RD,DALLAS,TX,75249,271023.0,94.0,18787,1998,71217,0,2.70
121,DAULTON/BERTHA CARO,6923,ROBIN RD,DALLAS,TX,75209,863507.0,92.0,72953,2013,127900,0,3.67
194,WIL;LIAM BARNETT II,13831,SUNDOWN TRAIL,FARMERS BRANCH,TX,75234,235585.0,92.0,19325,2019,37000,0,0.00
79,MAUDESTER LEE,1222,SERENADE LN,DALLAS,TX,75241,215178.0,90.0,24832,2002,55250,0,0.00
71,RAJAN P PATEL,3920-22,TRAVIS ST UNIT 2,DALLAS,TX,75204,488164.0,90.0,54166,2001,150400,0,0.00
14,ARAMINTA JOHNSON,1544,SUMMERS DR,CEDAR HILL,TX,75104,334420.0,90.0,37360,1999,131403,0,0.00
195,OSCAR C HERNANDEZ,4917,FRONTIER RD,GARLAND,TX,75043,175444.0,88.0,24276,2000,72000,0,0.00
114,SILVESTRE/MARIA TREJO,6928,CARIOCA PL,DALLAS,TX,75241,226358.0,88.0,30652,2021,30000,0,0.00
5,MISTY PAYNE,11220,PATTI LN,BALCH SPRINGS,TX,75180,183425.0,88.0,24915,2012,52425,328,4.00
283,JOEL PATTERSON,306,EAST KIMBROUGH ST,MESQUITE,FL,75149,272102.0,87.0,42188,2003,86400,0,0.00
22,ANCELMO/MARIA L VASQUEZ,1471,WEST RIM RD,DALLAS,TX,75211,282460.0,87.0,43000,2002,99280,0,0.00
296,DANIEL HOLGUIN ETAL,100,COLONIAL CIRCLE,SEAGOVILLE,TX,75159,239461.0,86.0,37699,2003,80900,0,0.00
11,NATOSHA HARRIS,825,WITHERSPOON CT,CEDAR HILL,TX,75104,241103.0,86.0,38337,2003,81809,0,0.00
31,MARIBEL CORONADO,2542,W FIVE MILE PKWY,DALLAS,TX,75233,322418.0,86.0,51552,2006,88000,0,0.00
97,ALICE A LINWOOD,10423,CHELMSFORD DR,DALLAS,TX,75217,185329.0,85.0,33701,2005,58225,0,0.00
212,LORENZO/ROSA M VALENZUELA,406,E CELESTE DR,GARLAND,TX,75041,210431.0,85.0,37339,2006,63000,0,0.00
93,GENEVIEVE BREMBRY,4209,BLACKHEATH RD,DALLAS,TX,75227,301178.0,84.0,57982,2003,120000,0,0.00
15,STEPHANIE SHEFFIELD ETAL,1401,JAMES ST,CEDAR HILL,TX,75104,276332.0,84.0,51478,2002,118044,0,0.00
100,ORSON B EDMOND,7319,LOST CANYON DR,DALLAS,TX,75249,266514.0,84.0,50966,2005,93600,0,0.00
36,JAMES W/LYNSEY PURL,9844,LANSHIRE DR,DALLAS,TX,75238,456725.0,84.0,89705,2005,160800,0,0.00
206,GONZALO MUNGUIA,2501,PECAN MEADOW DR,GARLAND,TX,75040,438053.0,83.0,86957,2005,158400,0,0.00
96,KEVIN WILEY,4039,FAWNHOLLOW DR,DALLAS,TX,75244,685240.0,83.0,136640,2004,272000,0,0.00
50,JESSIE VAUGHN,1235,HARLANDALE AVE,DALLAS,TX,75216,187008.0,83.0,39532,2015,45950,223,4.12
245,JACK SHASTID ETAL,1104,SHUFFORD ST,IRVING,TX,75060,266519.0,83.0,54361,2004,105600,0,0.00
10,MARIA GUARDADO ETAL,609,THORTON CT,CEDAR HILL,TX,75104,253089.0,82.0,57191,2006,99000,0,0.00
33,SOCORRO MARTINEZ ETAL,1314,GLENCLIFF DR,DALLAS,TX,75217,178698.0,82.0,38582,2002,86148,0,0.00
34,GREG WOLFKIEL,3959,ALTA VISTA LN,DALLAS,TX,75229,589996.0,82.0,131414,2004,254840,0,0.00
103,CARLEY R POTTS,9522,ALTA MIRA DR,DALLAS,TX,75218,662551.0,81.0,158539,2007,239100,1491,6.37
13,TRACY/DEMETRUS PARKER,908,RED OAK TRAILS,CEDAR HILL,TX,75104,260528.0,81.0,61062,2003,133898,0,0.00
204,CALVIN L SANDERS,1925,CARTMAN RD,GARLAND,TX,75040,296658.0,81.0,69342,2003,150915,0,0.00
254,RICARDO S JUAREZ ETAL,1110,TRACY LN,LANCASTER,TX,75134,189663.0,81.0,44567,2004,83074,0,0.00
185,S R MINSKY,602,LINKCREST CIR,DUNCANVILLE,TX,75137,288802.0,80.0,73228,2008,300000,1685,3.17
108,ORA/NATHANIEL TURNER,5822,LAKE PLACID DR,DALLAS,TX,75232,240099.0,80.0,61191,2004,122421,0,0.00
52,OLGA CANIZALES,9720,CALLE DEL ORO LN,DALLAS,TX,75217,222501.0,80.0,54689,2007,78375,506,6.70
59,RICARDO/MARIA L SERVIN,3222,SALERNO DR,DALLAS,TX,75224,182126.0,80.0,46464,2008,71039,0,0.00
101,MARY WHITE ETAL,7928,HULL AVE,DALLAS,TX,75216,168272.0,80.0,42938,2006,64500,419,6.75
288,ALBERT/CAROL POHL,819,BELT LINE RD,RICHARDSON,TX,75080,264320.0,80.0,66150,2006,105600,648,6.21
21,JAI B/CHERYL D POOLE,232,NIXON ST,COPPELL,TX,75019,230166.0,80.0,58834,2005,105499,0,0.00
234,KIMBERLY M ASTRAN,831,FAIR OAKS DR,GRAND PRAIRIE,TX,75052,304470.0,79.0,81760,2005,133192,824,6.29

In [447]:
DFW_Big_Equity_Info.rename(columns={'Mortgagor First Name': 'First Name', 'Mortgagor Last Name': 'Last Name'}, inplace=True)
DFW_Big_Equity_Info.head(60)

,Full Name,Street Number,Address,City Name,Owner State,Zip,Estimated Equity,Estimated Margin percent,Est Unpaid Bal,Loan Year,Original Loan Amount,Monthly Payment,Interest Rate
53,MARCUS D/COREY FURLOUGH,1846,E LEDBETTER DR,DALLAS,TX,75216,246979.0,99.0,3051,1993,40000,0,0.00
43,ANNIE HUFF,1928,MATAGORDA DR,DALLAS,TX,75232,324675.0,99.0,4305,1994,78937,0,0.00
7,WILFREDO PEREZ MENDEZ ET AL,3813,FOREST LAWN RD,BALCH SPRINGS,TX,75180,155460.0,99.0,1890,2016,0,1,0.00
216,CAMIE SANCHEZ ETAL,3114,MEDINA DR,GARLAND,TX,75041,361484.0,99.0,3186,2005,28200,0,0.00
261,DERRICK BATTS,1935,RYDER DR,LANCASTER,TX,75146,266035.0,99.0,2915,2006,23060,0,6.62
58,ARTURO GARCIA V,9905,HUSTEAD ST,DALLAS,TX,75217,207499.0,98.0,3351,1988,51719,0,0.00
239,CARLOS/CHRISTINA MORALES,1113,SHAWNEE TRACE,GRAND PRAIRIE,TX,75051,218568.0,98.0,5102,2006,68000,0,6.13
211,DAVID ARCHULETA,2413,HIGH STAR DR,GARLAND,TX,75041,261278.0,98.0,5242,2005,74395,0,0.00
106,KATHERINE/PETER STANTON,7829,EL PENSADOR DR,DALLAS,TX,75248,483964.0,98.0,10136,2009,178000,0,5.24
231,RODNEY DE BAUN ETAL,625,BEECHWOOD DR,GRAND PRAIRIE,TX,75052,229515.0,98.0,4255,1988,72638,0,0.00
236,SANTIAGO ZAMBRANO ETAL,626,AUSTIN ST,GRAND PRAIRIE,TX,75051,2148286.0,97.0,64654,2015,77569,360,3.75
61,JAMES JOHNSON,4446,CICERO ST,DALLAS,TX,75216,1141682.0,97.0,38598,2018,42000,200,3.95
129,MIRIAN FIERRO MEJIA ET AL,5007,BARTLETT AVE,DALLAS,TX,75216,129107.0,97.0,3663,2014,28000,285,4.10
203,GLEN BAILEY ETAL,1810,PATRICIA LN,GARLAND,TX,75042,269604.0,97.0,9196,1996,82873,0,0.00
18,RUSSELL M/JAMITA J MACHEN,1547,CYPRESS BEND DR,CEDAR HILL,TX,75104,636526.0,96.0,25464,2005,307500,0,0.00
12,TERRENCE G ORR,1038,HAMPSHIRE LN,CEDAR HILL,TX,75104,317915.0,96.0,12725,1996,110626,0,0.00
107,CASEY A BATES,4721,BRADFORD DR UNIT 4721B,DALLAS,TX,75219,2656896.0,96.0,103184,2006,175417,0,6.75
126,NaN,13735,BIGGS ST,DALLAS,TX,75253,342975.0,95.0,16635,2012,131200,0,3.97
159,HIRLA DANIELA MERCADO,3950,DEEP VALLEY DR,DALLAS,TX,75244,707891.0,95.0,40839,2017,60400,0,0.00
57,MARIA A/MIGUEL MARCELO,1619,ALASKA AVE,DALLAS,TX,75216,221795.0,95.0,11955,1998,50358,0,0.00
24,KUMESHA JACKSON,7502,RIDGEWICK DR,DALLAS,TX,75217,213386.0,94.0,12774,1999,39750,0,0.00
44,ALFONZO WADE ETAL,7119,CHINABERRY RD,DALLAS,TX,75249,271023.0,94.0,18787,1998,71217,0,2.70
121,DAULTON/BERTHA CARO,6923,ROBIN RD,DALLAS,TX,75209,863507.0,92.0,72953,2013,127900,0,3.67
194,WIL;LIAM BARNETT II,13831,SUNDOWN TRAIL,FARMERS BRANCH,TX,75234,235585.0,92.0,19325,2019,37000,0,0.00
79,MAUDESTER LEE,1222,SERENADE LN,DALLAS,TX,75241,215178.0,90.0,24832,2002,55250,0,0.00
71,RAJAN P PATEL,3920-22,TRAVIS ST UNIT 2,DALLAS,TX,75204,488164.0,90.0,54166,2001,150400,0,0.00
14,ARAMINTA JOHNSON,1544,SUMMERS DR,CEDAR HILL,TX,75104,334420.0,90.0,37360,1999,131403,0,0.00
195,OSCAR C HERNANDEZ,4917,FRONTIER RD,GARLAND,TX,75043,175444.0,88.0,24276,2000,72000,0,0.00
114,SILVESTRE/MARIA TREJO,6928,CARIOCA PL,DALLAS,TX,75241,226358.0,88.0,30652,2021,30000,0,0.00
5,MISTY PAYNE,11220,PATTI LN,BALCH SPRINGS,TX,75180,183425.0,88.0,24915,2012,52425,328,4.00
283,JOEL PATTERSON,306,EAST KIMBROUGH ST,MESQUITE,FL,75149,272102.0,87.0,42188,2003,86400,0,0.00
22,ANCELMO/MARIA L VASQUEZ,1471,WEST RIM RD,DALLAS,TX,75211,282460.0,87.0,43000,2002,99280,0,0.00
296,DANIEL HOLGUIN ETAL,100,COLONIAL CIRCLE,SEAGOVILLE,TX,75159,239461.0,86.0,37699,2003,80900,0,0.00
11,NATOSHA HARRIS,825,WITHERSPOON CT,CEDAR HILL,TX,75104,241103.0,86.0,38337,2003,81809,0,0.00
31,MARIBEL CORONADO,2542,W FIVE MILE PKWY,DALLAS,TX,75233,322418.0,86.0,51552,2006,88000,0,0.00
97,ALICE A LINWOOD,10423,CHELMSFORD DR,DALLAS,TX,75217,185329.0,85.0,33701,2005,58225,0,0.00
212,LORENZO/ROSA M VALENZUELA,406,E CELESTE DR,GARLAND,TX,75041,210431.0,85.0,37339,2006,63000,0,0.00
93,GENEVIEVE BREMBRY,4209,BLACKHEATH RD,DALLAS,TX,75227,301178.0,84.0,57982,2003,120000,0,0.00
15,STEPHANIE SHEFFIELD ETAL,1401,JAMES ST,CEDAR HILL,TX,75104,276332.0,84.0,51478,2002,118044,0,0.00
100,ORSON B EDMOND,7319,LOST CANYON DR,DALLAS,TX,75249,266514.0,84.0,50966,2005,93600,0,0.00
36,JAMES W/LYNSEY PURL,9844,LANSHIRE DR,DALLAS,TX,75238,456725.0,84.0,89705,2005,160800,0,0.00
206,GONZALO MUNGUIA,2501,PECAN MEADOW DR,GARLAND,TX,75040,438053.0,83.0,86957,2005,158400,0,0.00
96,KEVIN WILEY,4039,FAWNHOLLOW DR,DALLAS,TX,75244,685240.0,83.0,136640,2004,272000,0,0.00
50,JESSIE VAUGHN,1235,HARLANDALE AVE,DALLAS,TX,75216,187008.0,83.0,39532,2015,45950,223,4.12
245,JACK SHASTID ETAL,1104,SHUFFORD ST,IRVING,TX,75060,266519.0,83.0,54361,2004,105600,0,0.00
10,MARIA GUARDADO ETAL,609,THORTON CT,CEDAR HILL,TX,75104,253089.0,82.0,57191,2006,99000,0,0.00
33,SOCORRO MARTINEZ ETAL,1314,GLENCLIFF DR,DALLAS,TX,75217,178698.0,82.0,38582,2002,86148,0,0.00
34,GREG WOLFKIEL,3959,ALTA VISTA LN,DALLAS,TX,75229,589996.0,82.0,131414,2004,254840,0,0.00
103,CARLEY R POTTS,9522,ALTA MIRA DR,DALLAS,TX,75218,662551.0,81.0,158539,2007,239100,1491,6.37
13,TRACY/DEMETRUS PARKER,908,RED OAK TRAILS,CEDAR HILL,TX,75104,260528.0,81.0,61062,2003,133898,0,0.00
204,CALVIN L SANDERS,1925,CARTMAN RD,GARLAND,TX,75040,296658.0,81.0,69342,2003,150915,0,0.00
254,RICARDO S JUAREZ ETAL,1110,TRACY LN,LANCASTER,TX,75134,189663.0,81.0,44567,2004,83074,0,0.00
185,S R MINSKY,602,LINKCREST CIR,DUNCANVILLE,TX,75137,288802.0,80.0,73228,2008,300000,1685,3.17
108,ORA/NATHANIEL TURNER,5822,LAKE PLACID DR,DALLAS,TX,75232,240099.0,80.0,61191,2004,122421,0,0.00
52,OLGA CANIZALES,9720,CALLE DEL ORO LN,DALLAS,TX,75217,222501.0,80.0,54689,2007,78375,506,6.70
59,RICARDO/MARIA L SERVIN,3222,SALERNO DR,DALLAS,TX,75224,182126.0,80.0,46464,2008,71039,0,0.00
101,MARY WHITE ETAL,7928,HULL AVE,DALLAS,TX,75216,168272.0,80.0,42938,2006,64500,419,6.75
288,ALBERT/CAROL POHL,819,BELT LINE RD,RICHARDSON,TX,75080,264320.0,80.0,66150,2006,105600,648,6.21
21,JAI B/CHERYL D POOLE,232,NIXON ST,COPPELL,TX,75019,230166.0,80.0,58834,2005,105499,0,0.00
234,KIMBERLY M ASTRAN,831,FAIR OAKS DR,GRAND PRAIRIE,TX,75052,304470.0,79.0,81760,2005,133192,824,6.29

In [319]:
pd_series = pd.Series(data=['Jack','Daniel',3,'Engineering'], 
                      index=['First Name','Last Name','Siblings','Field'])

In [323]:
pd_series.shape

(4,)

In [383]:
pd_series

First Name           Jack
Last Name          Daniel
Siblings                3
Field         Engineering
dtype: object

In [397]:
print("This line represent example of \033[1mescape sequence\033[0m.")

This line represent example of escape sequence.