In [235]:
import pandas as pd

In [236]:
df = pd.read_csv('test.csv')

In [237]:
import os

In [238]:
print(os.getcwd())

C:\Users\admin

In [239]:
os.listdir()

['.ai-navigator',
 '.anaconda',
 '.astropy',
 '.atom',
 '.conda',
 '.condarc',
 '.continuum',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.matplotlib',
 '.nuget',
 '.thumbnails',
 '.VirtualBox',
 '.virtual_documents',
 '.vscode',
 '3d abc song chill',
 'anaconda_projects',
 'AppData',
 'Application Data',
 'Contacts',
 'Cookies',
 'Desktop',
 'DFWNov.csv',
 'DLX 2 ROCKY METAL LOUDER CYMBALS.ssd5kit',
 'Documents',
 'Downloads',
 'environment.yml',
 'Favorites',
 'GameMakerProjects',
 'IntelGraphicsProfiles',
 'jack.iom',
 'jacks.2ssd5kit.ssd5kit',
 'jacks.iom',
 'KIDS SHOW',
 'Links',
 'Local Settings',
 'Models and NPCs',
 'Music',
 'My Documents',
 'NCH Software Suite',
 'NetHood',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{a2332f18-cdbf-11ec-8680-002248483d79}.TM.blf',
 'NTUSER.DAT{a2332f18-cdbf-11ec-8680-002248483d79}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{a2332f18-cdbf-11ec-8680-002248483d79}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'PaceKeyChain',
 'Pictures',
 'PrintHood',
 'Proton Drive',
 'Recent',
 'Saved Games',
 'SciFi 3D',
 'Searches',
 'SendTo',
 'source',
 'Start Menu',
 'Templates',
 'test.csv',
 'Untitled.ipynb',
 'Untitled1.ipynb',
 'Untitled2.ipynb',
 'Untitled3.ipynb',
 'Videos']

In [240]:
df = pd.read_csv('DFWNov.csv')
df

,Estimated Equity,Estimated Margin percent,Est Unpaid Bal,Clerk Number,Year of Report,Month of Report,City Name,County Code,Mapsco Page,Mapsco Section,...,Owner Street Name,Owner Zip,Owner City,Owner State,Tax ID,Status,OpeningBid,Auction Date,Georeference,Zillow URL
0,289574.0,75.0,96706,0,2024,12,ADDISON,DA,NaN,NaN,...,PLANTERS ROW,75001,ADDISON,TX,100006500B0160000,NaN,0,December,http://www.zillow.com/homes/17073-PLANTERS-ROW...,NaN
1,NaN,NaN,0,0,2024,12,ADDISON,DA,NaN,NaN,...,BREEDLOVE PLACE #153,75001,ADDISON,TX,10C05500001700153,NaN,0,December,http://www.zillow.com/homes/15848-BREEDLOVE-PL...,NaN
2,NaN,NaN,0,0,2024,12,ADDISON,DA,NaN,NaN,...,SPECTRUM DR # 176,75001,ADDISON,TX,10C05500002000176,NaN,0,December,http://www.zillow.com/homes/15811-SPECTRUM-DR-...,NaN
3,235426.0,69.0,107444,0,2024,12,BALCH SPRINGS,DA,NaN,NaN,...,BROADVIEW DR,75180,BALCH SPRINGS,TX,120798000M0240000,NaN,0,December,http://www.zillow.com/homes/14718-BROADVIEW-DR...,NaN
4,108425.0,48.0,115535,0,2024,12,BALCH SPRINGS,DA,NaN,NaN,...,MARSHA DR,75180,BALCH SPRINGS,TX,12077500050260000,NaN,0,December,http://www.zillow.com/homes/14910-MARSHA-DR-N_rb/,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
293,NaN,NaN,0,0,2024,12,ROWLETT,DA,NaN,NaN,...,LIBERTY GROVE RD,75089,ROWLETT,TX,0,NaN,0,December,http://www.zillow.com/homes/10206-LIBERTY-GROV...,NaN
294,74963.0,23.0,246587,0,2024,12,SEAGOVILLE,DA,NaN,NaN,...,ARMSTRONG RD,75159,SEAGOVILLE,TX,500230000F0030000,NaN,0,December,http://www.zillow.com/homes/910-ARMSTRONG-RD-N...,NaN
295,72023.0,24.0,222307,0,2024,12,SEAGOVILLE,DA,NaN,NaN,...,S GREAT SOUTHWEST PKWY APT 134,75051,GRAND PRAIRIE,TX,50044500040010000,NaN,0,December,http://www.zillow.com/homes/531-JUDY-LN-N_rb/,NaN
296,239461.0,86.0,37699,0,2024,12,SEAGOVILLE,DA,NaN,NaN,...,COLONIAL CIR,75159,SEAGOVILLE,TX,50009920000010000,NaN,0,December,http://www.zillow.com/homes/100-COLONIAL-CIRCL...,NaN
297,60991.0,22.0,212429,0,2024,12,SUNNYVALE,DA,NaN,NaN,...,WIXOM LN,75217,DALLAS,TX,65123639010640000,NaN,0,December,http://www.zillow.com/homes/541-POLLY-RD-N_rb/,NaN

In [273]:
dfrev1 = df[[
    'Mortgagor First Name',
    'Mortgagor Last Name',
    'Owner Street Number',
    'Owner Street Name',
    'City Name',
    'Estimated Equity', 
    'Estimated Margin percent'
]][0:50]

dfrev1

,Mortgagor First Name,Mortgagor Last Name,Owner Street Number,Owner Street Name,City Name,Estimated Equity,Estimated Margin percent
0,DEANNA,PERKINS,17073,PLANTERS ROW,ADDISON,289574.0,75.0
1,MARC,HARPER,15848,BREEDLOVE PLACE #153,ADDISON,NaN,NaN
2,MICHAEL,BENJAMIN,15811,SPECTRUM DR # 176,ADDISON,NaN,NaN
3,KENDRICK D,ROSENDOLL,14718,BROADVIEW DR,BALCH SPRINGS,235426.0,69.0
4,ANDRES,DEL RIO TREJO,14910,MARSHA DR,BALCH SPRINGS,108425.0,48.0
5,MISTY,PAYNE,11220,PATTI LN,BALCH SPRINGS,183425.0,88.0
6,JUAN M,RICO ETAL,4324,MOHAWK DR,BALCH SPRINGS,92989.0,44.0
7,WILFREDO PEREZ,MENDEZ ET AL,3813,FOREST LAWN RD,BALCH SPRINGS,155460.0,99.0
8,MOSHE,ALMASI,2620,KIMBERLY CT,CARROLLTON,122587.0,27.0
9,LAUREN M/ARRON J,BOYLE,1012,ROSEWOOD PL,CARROLLTON,278611.0,77.0
10,MARIA,GUARDADO ETAL,3001,S CARRIER PKWY APT 902,CEDAR HILL,253089.0,82.0
11,NATOSHA,HARRIS,825,WITHERSPOON CT,CEDAR HILL,241103.0,86.0
12,TERRENCE G,ORR,1038,HAMPSHIRE LN,CEDAR HILL,317915.0,96.0
13,TRACY/DEMETRUS,PARKER,908,RED OAK TRAILS,CEDAR HILL,260528.0,81.0
14,ARAMINTA,JOHNSON,1544,SUMMERS DR,CEDAR HILL,334420.0,90.0
15,STEPHANIE,SHEFFIELD ETAL,1401,JAMES ST,CEDAR HILL,276332.0,84.0
16,MARTIN/MARISA,LAZALDE JR,1021,E WINTERGREEN RD,CEDAR HILL,234350.0,40.0
17,TIFFANIE,BLACKMON-JONES ETAL,7007,PORT PHILLIP DR,CEDAR HILL,209781.0,44.0
18,RUSSELL M/JAMITA J,MACHEN,1547,CYPRESS BEND DR,CEDAR HILL,636526.0,96.0
19,MARCELA,LEON,335,ASHLEY DR,COPPELL,362096.0,70.0
20,JOHN/LEXIE C,LEDBETTER,611,ST ANDREWS PL,COPPELL,308274.0,75.0
21,JAI B/CHERYL D,POOLE,232,NIXON ST,COPPELL,230166.0,80.0
22,ANCELMO/MARIA L,VASQUEZ,1471,WEST RIM RD,DALLAS,282460.0,87.0
23,MADALYNE C,CHILDRESS,4011,MARSHALL DR,DALLAS,34680.0,13.0
24,KUMESHA,JACKSON,7502,RIDGEWICK DR,DALLAS,213386.0,94.0
25,NaN,NUES LLC,415,E AIRPORT FWY STE 370,DALLAS,94038.0,14.0
26,KENYADA,SWITZER,14112,INDIAN WELLS RD,DALLAS,NaN,NaN
27,NaN,SIG GLOBAL LLC,2807,ALLEN ST PMB 2046,DALLAS,68953.0,45.0
28,HALEY,DEARMAN,5415,MELROSE AVE,DALLAS,561630.0,54.0
29,GUADALUPE/LUCIO,MORALES,9908,SANTA GARZA DR,DALLAS,NaN,NaN
30,ALBERTO,GUITERREZ JR ETAL,14203,RIATA LN,DALLAS,109719.0,37.0
31,MARIBEL,CORONADO,2542,W FIVE MILE PKWY,DALLAS,322418.0,86.0
32,CLARA A,CARTER,1915,PRAIRIE VIEW DR,DALLAS,124068.0,64.0
33,SOCORRO,MARTINEZ ETAL,1314,GLENCLIFF DR,DALLAS,178698.0,82.0
34,GREG,WOLFKIEL,3959,ALTA VISTA LN,DALLAS,589996.0,82.0
35,EZAI/YILLENNI,MARTINEZ,7102,HEDGE DR,DALLAS,95105.0,38.0
36,JAMES W/LYNSEY,PURL,9844,LANSHIRE DR,DALLAS,456725.0,84.0
37,MARIA,MONTOYA,10106,CUSHING DR,DALLAS,122463.0,38.0
38,DONNIE W,DEBERRY JR,3307,NEBRASKA AVE,DALLAS,121122.0,46.0
39,DYLAN T,HOFFMAN ETAL,3250,HIGHLAND WOODS CIR,DALLAS,14069.0,5.0
40,EDITH J,MARCOS,10821,LAKE GARDENS DR,DALLAS,NaN,NaN
41,NaN,DANCING KING PROPERTIES LLC,5010,BEEKMAN DR,DALLAS,NaN,NaN
42,CATHERINE,HENOJOSA,2339,GREAT LIGHT DR,DALLAS,176707.0,67.0
43,ANNIE,HUFF,1928,MATAGORDA DR,DALLAS,324675.0,99.0
44,ALFONZO,WADE ETAL,7119,CHINABERRY RD,DALLAS,271023.0,94.0
45,STEPHANIE/JACOB,WALTERS,10335,SANDRA LYNN DR,DALLAS,59446.0,20.0
46,ADRIANN T,MENDOZA,1533,E RED BIRD LN,DALLAS,140466.0,45.0
47,JOE/ELLEN P,GONZALES,4912,BERRIDGE LN,DALLAS,162753.0,74.0
48,SIMON/MARIA,GODINEZ,3515,PATIENCE BLVD,DALLAS,245984.0,43.0
49,PEDRO,GUERRERO ETAL,2015,MANHATTAN BEACH BLVD,DALLAS,161993.0,63.0

In [246]:
df.isnull().sum()

Estimated Equity             37
Estimated Margin percent     37
Est Unpaid Bal                0
Clerk Number                  0
Year of Report                0
Month of Report               0
City Name                     0
County Code                   0
Mapsco Page                 298
Mapsco Section              298
Class                         0
Loan Type                     0
Street Number                 0
Address                       0
B/B/G                         8
Property Sq Footage           0
Pool                         20
Zip                           0
Legal Description 1           0
Legal Description 2           1
Subdivision                   0
Mortgagor First Name         36
Mortgagor Last Name          28
Mortgagee                     0
Trustee                       0
Auction Sale Time             0
Volume                        0
Page                          0
Loan Month                    0
Loan Year                     0
Original Loan Amount          0
Monthly Payment               0
Interest Rate                 0
Loan Expires Month            0
Loan Expires Year             0
Year Of Construction          0
Assessed Value                0
City Code                     0
Number of Units               0
Previous Posting            171
Comment                     254
Owner Street Number           0
Owner Street Name             0
Owner Zip                     0
Owner City                    0
Owner State                   0
Tax ID                        0
Status                      298
OpeningBid                    0
Auction Date                  0
Georeference                  0
Zillow URL                  298
dtype: int64

In [248]:
df.isnull().sum().sum()

1784